//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ElementsOfTranslation() )+
    */
   public void visit(TranslationUnit n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ExternalDeclaration()
    *       | UnknownCpp()
    *       | UnknownPragma()
    */
   public void visit(ElementsOfTranslation n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Declaration()
    *       | FunctionDefinition()
    *       | OmpGlobalDirective()
    */
   public void visit(ExternalDeclaration n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( DeclarationSpecifiers() )?
    * f1 -> Declarator()
    * f2 -> ( DeclarationList() )?
    * f3 -> CompoundStatement()
    */
   public void visit(FunctionDefinition n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> DeclarationSpecifiers() ( InitDeclaratorList() )? ";"
    *       | StaticAssertDeclaration()
    */
   public void visit(Declaration n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STATIC_ASSERT>
    * f1 -> "("
    * f2 -> ConstantExpression()
    * f3 -> ","
    * f4 -> <STRING_LITERAL>
    * f5 -> ")"
    */
   public void visit(StaticAssertDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> ( Declaration() )+
    */
   public void visit(DeclarationList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( ADeclarationSpecifier() )+
    */
   public void visit(DeclarationSpecifiers n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> StorageClassSpecifier()
    *       | TypeSpecifier()
    *       | TypeQualifier()
    *       | FunctionSpecifier()
    *       | AlignmentSpecifier()
    */
   public void visit(ADeclarationSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INLINE>
    *       | <NORETURN>
    */
   public void visit(FunctionSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> AlignAsTypeName()
    *       | AlignAsConstantExpression()
    */
   public void visit(AlignmentSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <ALIGNAS>
    * f1 -> "("
    * f2 -> TypeName()
    * f3 -> ")"
    */
   public void visit(AlignAsTypeName n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <ALIGNAS>
    * f1 -> "("
    * f2 -> ConstantExpression()
    * f3 -> ")"
    */
   public void visit(AlignAsConstantExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <AUTO>
    *       | <REGISTER>
    *       | <STATIC>
    *       | <EXTERN>
    *       | <TYPEDEF>
    */
   public void visit(StorageClassSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <VOID> | <CHAR> | <SHORT> | <INT> | <LONG> | <FLOAT> | <DOUBLE> | <SIGNED> | <UNSIGNED> | StructOrUnionSpecifier() | EnumSpecifier() | TypedefName() )
    */
   public void visit(TypeSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <RESTRICT>
    *       | <CONST>
    *       | <VOLATILE>
    *       | <CCONST>
    *       | <CSIGNED>
    *       | <CSIGNED2>
    */
   public void visit(TypeQualifier n) {
      n.f0.accept(this);
   }

   /**

    * f0 -> ( StructOrUnionSpecifierWithList() | StructOrUnionSpecifierWithId() )
    */
   public void visit(StructOrUnionSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> StructOrUnion()
    * f1 -> ( <IDENTIFIER> )?
    * f2 -> "{"
    * f3 -> StructDeclarationList()
    * f4 -> "}"
    */
   public void visit(StructOrUnionSpecifierWithList n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> StructOrUnion()
    * f1 -> <IDENTIFIER>
    */
   public void visit(StructOrUnionSpecifierWithId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <STRUCT>
    *       | <UNION>
    */
   public void visit(StructOrUnion n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( StructDeclaration() )+
    */
   public void visit(StructDeclarationList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( "," InitDeclarator() )*
    */
   public void visit(InitDeclaratorList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Declarator()
    * f1 -> ( "=" Initializer() )?
    */
   public void visit(InitDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> StructDeclaratorList()
    * f2 -> ";"
    */
   public void visit(StructDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> ( ASpecifierQualifier() )+
    */
   public void visit(SpecifierQualifierList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> TypeSpecifier()
    *       | TypeQualifier()
    */
   public void visit(ASpecifierQualifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> StructDeclarator()
    * f1 -> ( "," StructDeclarator() )*
    */
   public void visit(StructDeclaratorList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> StructDeclaratorWithDeclarator()
    *       | StructDeclaratorWithBitField()
    */
   public void visit(StructDeclarator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Declarator()
    * f1 -> ( ":" ConstantExpression() )?
    */
   public void visit(StructDeclaratorWithDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ":"
    * f1 -> ConstantExpression()
    */
   public void visit(StructDeclaratorWithBitField n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> EnumSpecifierWithList()
    *       | EnumSpecifierWithId()
    */
   public void visit(EnumSpecifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <ENUM>
    * f1 -> ( <IDENTIFIER> )?
    * f2 -> "{"
    * f3 -> EnumeratorList()
    * f4 -> "}"
    */
   public void visit(EnumSpecifierWithList n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <ENUM>
    * f1 -> <IDENTIFIER>
    */
   public void visit(EnumSpecifierWithId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Enumerator()
    * f1 -> ( "," Enumerator() )*
    */
   public void visit(EnumeratorList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "=" ConstantExpression() )?
    */
   public void visit(Enumerator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( Pointer() )?
    * f1 -> DirectDeclarator()
    */
   public void visit(Declarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> IdentifierOrDeclarator()
    * f1 -> DeclaratorOpList()
    */
   public void visit(DirectDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( ADeclaratorOp() )*
    */
   public void visit(DeclaratorOpList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> DimensionSize()
    *       | ParameterTypeListClosed()
    *       | OldParameterListClosed()
    */
   public void visit(ADeclaratorOp n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "["
    * f1 -> ( ConstantExpression() )?
    * f2 -> "]"
    */
   public void visit(DimensionSize n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> ( ParameterTypeList() )?
    * f2 -> ")"
    */
   public void visit(ParameterTypeListClosed n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> ( OldParameterList() )?
    * f2 -> ")"
    */
   public void visit(OldParameterListClosed n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    *       | "(" Declarator() ")"
    */
   public void visit(IdentifierOrDeclarator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( "*" | "^" )
    * f1 -> ( TypeQualifierList() )?
    * f2 -> ( Pointer() )?
    */
   public void visit(Pointer n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> ( TypeQualifier() )+
    */
   public void visit(TypeQualifierList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ParameterList()
    * f1 -> ( "," "..." )?
    */
   public void visit(ParameterTypeList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public void visit(ParameterList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ParameterAbstraction()
    */
   public void visit(ParameterDeclaration n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Declarator()
    *       | AbstractOptionalDeclarator()
    */
   public void visit(ParameterAbstraction n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( AbstractDeclarator() )?
    */
   public void visit(AbstractOptionalDeclarator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public void visit(OldParameterList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AssignmentExpression()
    *       | ArrayInitializer()
    */
   public void visit(Initializer n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> InitializerList()
    * f2 -> ( "," )?
    * f3 -> "}"
    */
   public void visit(ArrayInitializer n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> Initializer()
    * f1 -> ( "," Initializer() )*
    */
   public void visit(InitializerList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> ( AbstractDeclarator() )?
    */
   public void visit(TypeName n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AbstractDeclaratorWithPointer()
    *       | DirectAbstractDeclarator()
    */
   public void visit(AbstractDeclarator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Pointer()
    * f1 -> ( DirectAbstractDeclarator() )?
    */
   public void visit(AbstractDeclaratorWithPointer n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AbstractDimensionOrParameter()
    * f1 -> DimensionOrParameterList()
    */
   public void visit(DirectAbstractDeclarator n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AbstractDeclaratorClosed()
    *       | DimensionSize()
    *       | ParameterTypeListClosed()
    */
   public void visit(AbstractDimensionOrParameter n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> AbstractDeclarator()
    * f2 -> ")"
    */
   public void visit(AbstractDeclaratorClosed n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> ( ADimensionOrParameter() )*
    */
   public void visit(DimensionOrParameterList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> DimensionSize()
    *       | ParameterTypeListClosed()
    */
   public void visit(ADimensionOrParameter n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(TypedefName n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> LabeledStatement()
    *       | ExpressionStatement()
    *       | CompoundStatement()
    *       | SelectionStatement()
    *       | IterationStatement()
    *       | JumpStatement()
    *       | UnknownPragma()
    *       | OmpConstruct()
    *       | OmpDirective()
    *       | UnknownCpp()
    */
   public void visit(Statement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> SimpleLabeledStatement()
    *       | CaseLabeledStatement()
    *       | DefaultLabeledStatement()
    */
   public void visit(LabeledStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public void visit(SimpleLabeledStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <CASE>
    * f1 -> ConstantExpression()
    * f2 -> ":"
    * f3 -> Statement()
    */
   public void visit(CaseLabeledStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <DFLT>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public void visit(DefaultLabeledStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> ( Expression() )?
    * f1 -> ";"
    */
   public void visit(ExpressionStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> ( CompoundStatementElement() )*
    * f2 -> "}"
    */
   public void visit(CompoundStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> Declaration()
    *       | Statement()
    */
   public void visit(CompoundStatementElement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> IfStatement()
    *       | SwitchStatement()
    */
   public void visit(SelectionStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> ( <ELSE> Statement() )?
    */
   public void visit(IfStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <SWITCH>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(SwitchStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> WhileStatement()
    *       | DoStatement()
    *       | ForStatement()
    */
   public void visit(IterationStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <WHILE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(WhileStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <DO>
    * f1 -> Statement()
    * f2 -> <WHILE>
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public void visit(DoStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> ( Expression() )?
    * f3 -> ";"
    * f4 -> ( Expression() )?
    * f5 -> ";"
    * f6 -> ( Expression() )?
    * f7 -> ")"
    * f8 -> Statement()
    */
   public void visit(ForStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> GotoStatement()
    *       | ContinueStatement()
    *       | BreakStatement()
    *       | ReturnStatement()
    */
   public void visit(JumpStatement n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <GOTO>
    * f1 -> <IDENTIFIER>
    * f2 -> ";"
    */
   public void visit(GotoStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <CONTINUE>
    * f1 -> ";"
    */
   public void visit(ContinueStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <BREAK>
    * f1 -> ";"
    */
   public void visit(BreakStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <RETURN>
    * f1 -> ( Expression() )?
    * f2 -> ";"
    */
   public void visit(ReturnStatement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "#"
    * f1 -> <UNKNOWN_CPP>
    */
   public void visit(UnknownCpp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <OMP_CR>
    *       | <OMP_NL>
    */
   public void visit(OmpEol n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpParallelConstruct()
    *       | OmpForConstruct()
    *       | OmpSectionsConstruct()
    *       | OmpSingleConstruct()
    *       | OmpSimdConstruct()
    *       | OmpForSimdConstruct()
    *       | OmpTaskConstruct()
    *       | OmpTaskLoopSimdConstruct()
    *       | OmpTaskLoopConstruct()
    *       | OmpTargetDataConstruct()
    *       | OmpTargetParallelForSimdConstruct()
    *       | OmpTargetParallelForConstruct()
    *       | OmpTargetParallelConstruct()
    *       | OmpTargetSimdConstruct()
    *       | OmpTargetTeamsDistributeParallelForSimdConstruct()
    *       | OmpTargetTeamsDistributeParallelForConstruct()
    *       | OmpTargetTeamsDistributeSimdConstruct()
    *       | OmpTargetTeamsDistributeConstruct()
    *       | OmpTargetTeamsConstruct()
    *       | OmpTargetConstruct()
    *       | OmpTeamsDistributeParallelForSimdConstruct()
    *       | OmpTeamsDistributeParallelForConstruct()
    *       | OmpTeamsDistributeSimdConstruct()
    *       | OmpTeamsDistributeConstruct()
    *       | OmpTeamsConstruct()
    *       | OmpDistributeSimdConstruct()
    *       | OmpDistributeParallelForSimdConstruct()
    *       | OmpDistributeParallelForConstruct()
    *       | OmpDistributeConstruct()
    *       | OmpParallelForSimdConstruct()
    *       | OmpParallelForConstruct()
    *       | OmpParallelSectionsConstruct()
    *       | OmpMasterConstruct()
    *       | OmpCriticalConstruct()
    *       | OmpTaskGroupConstruct()
    *       | OmpAtomicConstruct()
    *       | OmpOrderedConstruct()
    */
   public void visit(OmpConstruct n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpTaskyieldDirective()
    *       | OmpTargetEnterDataDirective()
    *       | OmpTargetExitDataDirective()
    *       | OmpTargetUpdateDirective()
    *       | OmpBarrierDirective()
    *       | OmpTaskwaitDirective()
    *       | OmpFlushDirective()
    *       | OmpCancelDirective()
    *       | OmpCancellationPointDirective()
    */
   public void visit(OmpDirective n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "#"
    * f1 -> <PRAGMA>
    * f2 -> <OMP>
    */
   public void visit(OmpPragma n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "#"
    * f1 -> <PRAGMA>
    * f2 -> <UNKNOWN_CPP>
    */
   public void visit(UnknownPragma n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> ( OmpParallelClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpParallelConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpParallelClause()
    * f1 -> ( ( "," )? OmpParallelClause() )*
    */
   public void visit(OmpParallelClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpCopyinClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    */
   public void visit(OmpParallelClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <PARALLEL> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfParallelClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <NUM_THREADS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpNumThreadsClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <DFLT>
    * f1 -> "("
    * f2 -> <SHARED>
    * f3 -> ")"
    */
   public void visit(OmpDfltSharedClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <DFLT>
    * f1 -> "("
    * f2 -> <NONE>
    * f3 -> ")"
    */
   public void visit(OmpDfltNoneClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <PRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpPrivateClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <FIRSTPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpFirstPrivateClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <SHARED>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpSharedClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <COPYIN>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpCopyinClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <REDUCTION>
    * f1 -> "("
    * f2 -> ReductionOp()
    * f3 -> ":"
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public void visit(OmpReductionClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <MASTER>
    * f3 -> ")"
    */
   public void visit(OmpThreadAffinityMasterClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <CLOSE>
    * f3 -> ")"
    */
   public void visit(OmpThreadAffinityCloseClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <SPREAD>
    * f3 -> ")"
    */
   public void visit(OmpThreadAffinitySpreadClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <FOR>
    * f2 -> ( OmpForClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpForConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpForClause()
    * f1 -> ( ( "," )? OmpForClause() )*
    */
   public void visit(OmpForClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpReductionClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpForClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <LASTPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpLastPrivateClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <LINEAR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ( <COLON> Expression() )?
    * f4 -> ")"
    */
   public void visit(OmpLinearClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <SCHEDULE>
    * f1 -> "("
    * f2 -> ( Modifier() ( "," Modifier() )? <COLON> )?
    * f3 -> ScheduleKind()
    * f4 -> ( "," Expression() )?
    * f5 -> ")"
    */
   public void visit(OmpScheduleClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <MONOTONIC>
    *       | <NONMONOTONIC>
    *       | <SIMD>
    */
   public void visit(Modifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STATIC>
    *       | <DYNAMIC>
    *       | <GUIDED>
    *       | <RUNTIME>
    *       | <AUTO>
    */
   public void visit(ScheduleKind n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <COLLAPSE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpCollapseClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <ORDERED>
    * f1 -> ( "(" Expression() ")" )?
    */
   public void visit(OmpOrderedClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <NOWAIT>
    */
   public void visit(OmpNowaitClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> OmpForInitExpression()
    * f3 -> ";"
    * f4 -> OmpForCondition()
    * f5 -> ";"
    * f6 -> OmpForReinitExpression()
    * f7 -> ")"
    */
   public void visit(OmpForHeader n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> Expression()
    */
   public void visit(OmpForInitExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpForLTCondition()
    *       | OmpForLECondition()
    *       | OmpForGTCondition()
    *       | OmpForGECondition()
    */
   public void visit(OmpForCondition n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "<"
    * f2 -> Expression()
    */
   public void visit(OmpForLTCondition n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "<="
    * f2 -> Expression()
    */
   public void visit(OmpForLECondition n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ">"
    * f2 -> Expression()
    */
   public void visit(OmpForGTCondition n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ">="
    * f2 -> Expression()
    */
   public void visit(OmpForGECondition n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> PostIncrementId()
    *       | PostDecrementId()
    *       | PreIncrementId()
    *       | PreDecrementId()
    *       | ShortAssignPlus()
    *       | ShortAssignMinus()
    *       | OmpForAdditive()
    *       | OmpForSubtractive()
    *       | OmpForMultiplicative()
    */
   public void visit(OmpForReinitExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "++"
    */
   public void visit(PostIncrementId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "--"
    */
   public void visit(PostDecrementId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "++"
    * f1 -> <IDENTIFIER>
    */
   public void visit(PreIncrementId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "--"
    * f1 -> <IDENTIFIER>
    */
   public void visit(PreDecrementId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "+="
    * f2 -> Expression()
    */
   public void visit(ShortAssignPlus n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "-="
    * f2 -> Expression()
    */
   public void visit(ShortAssignMinus n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> <IDENTIFIER>
    * f3 -> "+"
    * f4 -> AdditiveExpression()
    */
   public void visit(OmpForAdditive n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> <IDENTIFIER>
    * f3 -> "-"
    * f4 -> AdditiveExpression()
    */
   public void visit(OmpForSubtractive n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> MultiplicativeExpression()
    * f3 -> "+"
    * f4 -> <IDENTIFIER>
    */
   public void visit(OmpForMultiplicative n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <SECTIONS>
    * f2 -> ( OmpSectionsClauseList() )?
    * f3 -> OmpEol()
    * f4 -> SectionsScope()
    */
   public void visit(OmpSectionsConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpSectionsClause()
    * f1 -> ( ( "," )? OmpSectionsClause() )*
    */
   public void visit(OmpSectionsClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpReductionClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpSectionsClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )?
    * f2 -> ( ASection() )*
    * f3 -> "}"
    */
   public void visit(SectionsScope n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <SECTION>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public void visit(ASection n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <SINGLE>
    * f2 -> ( OmpSingleClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpSingleConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpSingleClause()
    * f1 -> ( OmpSingleClause() )*
    */
   public void visit(OmpSingleClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpCopyPrivateClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpSingleClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <COPYPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpCopyPrivateClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <SIMD>
    * f2 -> ( OmpSimdClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpSimdClause()
    * f1 -> ( ( "," )? OmpSimdClause() )*
    */
   public void visit(OmpSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpSafeLenClause()
    *       | OmpSimdLenClause()
    *       | OmpLinearClause()
    *       | OmpAlignedClause()
    *       | OmpPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpReductionClause()
    *       | OmpCollapseClause()
    */
   public void visit(OmpSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <SAFELEN>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpSafeLenClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <SIMDLEN>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpSimdLenClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <ALIGNED>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ( <COLON> Expression() )?
    * f4 -> ")"
    */
   public void visit(OmpAlignedClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <FOR>
    * f2 -> <SIMD>
    * f3 -> ( OmpForSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpForSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> OmpForSimdClause()
    * f1 -> ( ( "," )? OmpForSimdClause() )*
    */
   public void visit(OmpForSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpSimdClause()
    *       | OmpForClause()
    */
   public void visit(OmpForSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASK>
    * f2 -> ( TaskClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpTaskConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> TaskClause()
    * f1 -> ( ( "," )? TaskClause() )*
    */
   public void visit(TaskClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTaskClause()
    *       | OmpFinalClause()
    *       | OmpUntiedClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpMergeableClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpDependClause()
    *       | OmpPriorityClause()
    */
   public void visit(TaskClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TASK> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTaskClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <FINAL>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpFinalClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <UNTIED>
    */
   public void visit(OmpUntiedClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <MERGEABLE>
    */
   public void visit(OmpMergeableClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> DependencyType()
    * f3 -> <COLON>
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public void visit(OmpDependClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <IN>
    *       | <OUT>
    *       | <INOUT>
    */
   public void visit(DependencyType n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <PRIORITY>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpPriorityClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKLOOP>
    * f2 -> <SIMD>
    * f3 -> ( OmpTaskLoopSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpTaskLoopSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> OmpTaskLoopSimdClause()
    * f1 -> ( ( "," )? OmpTaskLoopSimdClause() )*
    */
   public void visit(OmpTaskLoopSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpSimdClause()
    *       | OmpTaskLoopClause()
    */
   public void visit(OmpTaskLoopSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKLOOP>
    * f2 -> ( OmpTaskLoopClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpTaskLoopConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpTaskLoopClause()
    * f1 -> ( ( "," )? OmpTaskLoopClause() )*
    */
   public void visit(OmpTaskLoopClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTaskLoopClause()
    *       | OmpSharedClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpGrainSizeClause()
    *       | OmpNumTasksClause()
    *       | OmpCollapseClause()
    *       | OmpFinalClause()
    *       | OmpPriorityClause()
    *       | OmpUntiedClause()
    *       | OmpMergeableClause()
    *       | OmpNoGroupClause()
    */
   public void visit(OmpTaskLoopClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TASKLOOP> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTaskLoopClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <GRAINSIZE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpGrainSizeClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <NUMTASKS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpNumTasksClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <NOGROUP>
    */
   public void visit(OmpNoGroupClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <DATA>
    * f3 -> ( OmpTargetDataClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public void visit(OmpTargetDataConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpTargetDataClause()
    * f1 -> ( ( "," )? OmpTargetDataClause() )*
    */
   public void visit(OmpTargetDataClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTargetDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpUseDevicePtrClause()
    */
   public void visit(OmpTargetDataClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> <TARGET>
    * f3 -> <DATA>
    * f4 -> Expression()
    * f5 -> ")"
    */
   public void visit(OmpIfTargetDataClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <USEDEVICEPTR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpUseDevicePtrClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> <SIMD>
    * f5 -> ( OmpTargetParallelForSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpTargetParallelForSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> OmpTargetParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTargetParallelForSimdClause() )*
    */
   public void visit(OmpTargetParallelForSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpSimdClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpTargetParallelForSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> ( OmpTargetParallelForClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpTargetParallelForConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> OmpTargetParallelForClause()
    * f1 -> ( ( "," )? OmpTargetParallelForClause() )*
    */
   public void visit(OmpTargetParallelForClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpTargetParallelForClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> ( OmpTargetParallelClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public void visit(OmpTargetParallelConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpTargetParallelClause()
    * f1 -> ( ( "," )? OmpTargetParallelClause() )*
    */
   public void visit(OmpTargetParallelClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    */
   public void visit(OmpTargetParallelClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <SIMD>
    * f3 -> ( OmpTargetSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpTargetSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> OmpTargetSimdClause()
    * f1 -> ( ( "," )? OmpTargetSimdClause() )*
    */
   public void visit(OmpTargetSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpSimdClause()
    */
   public void visit(OmpTargetSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> <SIMD>
    * f6 -> ( OmpTargetTeamsDistributeParallelForSimdClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeParallelForSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
   }

   /**
    * f0 -> OmpTargetTeamsDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeParallelForSimdClause() )*
    */
   public void visit(OmpTargetTeamsDistributeParallelForSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeParallelForSimdClause()
    */
   public void visit(OmpTargetTeamsDistributeParallelForSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> <PARALLEL>
    * f5 -> <FOR>
    * f6 -> ( OmpTargetTeamsDistributeParallelForClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeParallelForConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
   }

   /**
    * f0 -> OmpTargetTeamsDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeParallelForClause() )*
    */
   public void visit(OmpTargetTeamsDistributeParallelForClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeParallelForClause()
    */
   public void visit(OmpTargetTeamsDistributeParallelForClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> <SIMD>
    * f5 -> ( OmpTargetTeamsDistributeSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> OmpTargetTeamsDistributeSimdClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeSimdClause() )*
    */
   public void visit(OmpTargetTeamsDistributeSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeSimdClause()
    */
   public void visit(OmpTargetTeamsDistributeSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> ( OmpTargetTeamsDistributeClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> OmpTargetTeamsDistributeClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeClause() )*
    */
   public void visit(OmpTargetTeamsDistributeClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeClause()
    */
   public void visit(OmpTargetTeamsDistributeClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> ( OmpTargetTeamsClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public void visit(OmpTargetTeamsConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpTargetTeamsClause()
    * f1 -> ( ( "," )? OmpTargetTeamsClause() )*
    */
   public void visit(OmpTargetTeamsClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsClause()
    */
   public void visit(OmpTargetTeamsClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> ( OmpTargetClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpTargetConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpTargetClause()
    * f1 -> ( ( "," )? OmpTargetClause() )*
    */
   public void visit(OmpTargetClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTargetClause()
    *       | OmpDeviceClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpMapClause()
    *       | OmpIsDevicePtrListClause()
    *       | OmpDefaultMapClause()
    *       | OmpNowaitClause()
    *       | OmpDependClause()
    */
   public void visit(OmpTargetClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <ISDEVICEPTR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpIsDevicePtrListClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <DEFAULTMAP>
    * f1 -> "("
    * f2 -> <TOFROM>
    * f3 -> <COLON>
    * f4 -> <SCALAR>
    * f5 -> ")"
    */
   public void visit(OmpDefaultMapClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> <SIMD>
    * f6 -> ( OmpTeamsDistributeParallelForSimdClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public void visit(OmpTeamsDistributeParallelForSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
   }

   /**
    * f0 -> OmpTeamsDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeParallelForSimdClause() )*
    */
   public void visit(OmpTeamsDistributeParallelForSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeParallelForSimdClause()
    */
   public void visit(OmpTeamsDistributeParallelForSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> ( OmpTeamsDistributeParallelForClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpTeamsDistributeParallelForConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> OmpTeamsDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeParallelForClause() )*
    */
   public void visit(OmpTeamsDistributeParallelForClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeParallelForClause()
    */
   public void visit(OmpTeamsDistributeParallelForClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <SIMD>
    * f4 -> ( OmpTeamsDistributeSimdClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpTeamsDistributeSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> OmpTeamsDistributeSimdClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeSimdClause() )*
    */
   public void visit(OmpTeamsDistributeSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeSimdClause()
    */
   public void visit(OmpTeamsDistributeSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> ( OmpTeamsDistributeClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpTeamsDistributeConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> OmpTeamsDistributeClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeClause() )*
    */
   public void visit(OmpTeamsDistributeClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeClause()
    */
   public void visit(OmpTeamsDistributeClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> ( OmpTeamsClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpTeamsConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpTeamsClause()
    * f1 -> ( ( "," )? OmpTeamsClause() )*
    */
   public void visit(OmpTeamsClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpNumTeamsClause()
    *       | OmpThreadLimitClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    */
   public void visit(OmpTeamsClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <NUMTEAMS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpNumTeamsClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <THREADLIMIT>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpThreadLimitClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <SIMD>
    * f3 -> ( OmpDistributeSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpDistributeSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> OmpDistributeSimdClause()
    * f1 -> ( ( "," )? OmpDistributeSimdClause() )*
    */
   public void visit(OmpDistributeSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpSimdClause()
    */
   public void visit(OmpDistributeSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> <SIMD>
    * f5 -> ( OmpDistributeParallelForSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpDistributeParallelForSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> OmpDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpDistributeParallelForSimdClause() )*
    */
   public void visit(OmpDistributeParallelForSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpParallelForSimdClause()
    */
   public void visit(OmpDistributeParallelForSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> ( OmpDistributeParallelForClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpDistributeParallelForConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> OmpDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpDistributeParallelForClause() )*
    */
   public void visit(OmpDistributeParallelForClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpParallelForClause()
    */
   public void visit(OmpDistributeParallelForClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> ( OmpDistributeClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpDistributeConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpDistributeClause()
    * f1 -> ( ( "," )? OmpDistributeClause() )*
    */
   public void visit(OmpDistributeClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpCollapseClause()
    *       | OmpDistScheduleClause()
    */
   public void visit(OmpDistributeClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <DISTSCHEDULE>
    * f1 -> "("
    * f2 -> ScheduleKind()
    * f3 -> ( "," Expression() )?
    * f4 -> ")"
    */
   public void visit(OmpDistScheduleClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <FOR>
    * f3 -> <SIMD>
    * f4 -> ( OmpParallelForSimdClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpParallelForSimdConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> OmpParallelForSimdClause()
    * f1 -> ( ( "," )? OmpParallelForSimdClause() )*
    */
   public void visit(OmpParallelForSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpParallelClause()
    *       | OmpSimdClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpParallelForSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <FOR>
    * f3 -> ( OmpParallelForClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpParallelForConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> OmpParallelForClause()
    * f1 -> ( ( "," )? OmpParallelForClause() )*
    */
   public void visit(OmpParallelForClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpParallelClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpParallelForClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <SECTIONS>
    * f3 -> ( OmpParallelSectionsClauseList() )?
    * f4 -> OmpEol()
    * f5 -> SectionsScope()
    */
   public void visit(OmpParallelSectionsConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpParallelClause()
    *       | OmpLastPrivateClause()
    */
   public void visit(OmpParallelSectionsClauseList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <MASTER>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public void visit(OmpMasterConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <CRITICAL>
    * f2 -> ( "(" OmpCriticalName() ")" ( <HINT> "(" Expression() ")" )? )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpCriticalConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> <IDENTIFIER>
    * f2 -> ")"
    */
   public void visit(OmpCriticalName n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKGROUP>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public void visit(OmpTaskGroupConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpAtomicDefaultConstruct()
    *       | OmpAtomicClauseConstruct()
    */
   public void visit(OmpAtomicConstruct n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <ATOMIC>
    * f2 -> ( <SEQCST> ( "," )? )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpAtomicDefaultConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <ATOMIC>
    * f2 -> ( <SEQCST> ( "," )? )?
    * f3 -> AtomicClause()
    * f4 -> ( <SEQCST> ( "," )? )?
    * f5 -> OmpEol()
    * f6 -> Statement()
    */
   public void visit(OmpAtomicClauseConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> <READ>
    *       | <WRITE>
    *       | <UPDATE>
    *       | <CAPTURE>
    */
   public void visit(AtomicClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <ORDERED>
    * f2 -> ( OmpOrderedClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpOrderedConstruct n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpOrderedConstructClause()
    * f1 -> ( ( "," )? OmpOrderedConstructClause() )*
    */
   public void visit(OmpOrderedClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpThreadsClause()
    *       | OmpSimdOrderedClause()
    *       | OmpDependOrderedSourceClause()
    *       | OmpDependOrderedSinkClause()
    */
   public void visit(OmpOrderedConstructClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <THREADS>
    */
   public void visit(OmpThreadsClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <SIMD>
    */
   public void visit(OmpSimdOrderedClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> <SOURCE>
    * f3 -> ")"
    */
   public void visit(OmpDependOrderedSourceClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> <SINK>
    * f3 -> <COLON>
    * f4 -> OmpIterationVector()
    * f5 -> ")"
    */
   public void visit(OmpDependOrderedSinkClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpIterationDimension()
    * f1 -> ( "," OmpIterationDimension() )*
    */
   public void visit(OmpIterationVector n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpForwardDependence()
    *       | OmpBackwardDependence()
    */
   public void visit(OmpIterationDimension n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "+"
    * f2 -> ConstantExpression()
    */
   public void visit(OmpForwardDependence n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "-"
    * f2 -> ConstantExpression()
    */
   public void visit(OmpBackwardDependence n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKYIELD>
    * f2 -> OmpEol()
    */
   public void visit(OmpTaskyieldDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <ENTER>
    * f3 -> <DATA>
    * f4 -> ( OmpTargetEnterDataClauseList() )?
    */
   public void visit(OmpTargetEnterDataDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpTargetEnterDataClause()
    * f1 -> ( ( "," )? OmpTargetEnterDataClause() )*
    */
   public void visit(OmpTargetEnterDataClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTargetEnterDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpDependClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpTargetEnterDataClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <ENTER> <DATA> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetEnterDataClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <DEVICE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpDeviceClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <MAP>
    * f1 -> "("
    * f2 -> ( ( OmpMapTypeModifier() ( "," )? )? OmpMapType() <COLON> )?
    * f3 -> VariableList()
    * f4 -> ")"
    */
   public void visit(OmpMapClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <ALWAYS>
    */
   public void visit(OmpMapTypeModifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <TO>
    *       | <FROM>
    *       | <TOFROM>
    *       | <ALLOC>
    *       | <RELEASE>
    *       | <DELETE>
    */
   public void visit(OmpMapType n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <EXIT>
    * f3 -> <DATA>
    * f4 -> ( OmpTargetExitDataClauseList() )?
    */
   public void visit(OmpTargetExitDataDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpTargetExitDataClause()
    * f1 -> ( ( "," )? OmpTargetExitDataClause() )*
    */
   public void visit(OmpTargetExitDataClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTargetExitDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpDependClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpTargetExitDataClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <EXIT> <DATA> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetExitDataClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <UPDATE>
    * f3 -> OmpTargetUpdateClauseList()
    */
   public void visit(OmpTargetUpdateDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpTargetUpdateClause()
    * f1 -> ( ( "," )? OmpTargetUpdateClause() )*
    */
   public void visit(OmpTargetUpdateClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpIfTargetUpdateClause()
    *       | OmpDeviceClause()
    *       | OmpNowaitClause()
    *       | OmpDependClause()
    *       | OmpToClause()
    *       | OmpFromClause()
    */
   public void visit(OmpTargetUpdateClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <UPDATE> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetUpdateClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <TO>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpToClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <FROM>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpFromClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <BARRIER>
    * f2 -> OmpEol()
    */
   public void visit(OmpBarrierDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKWAIT>
    * f2 -> OmpEol()
    */
   public void visit(OmpTaskwaitDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <FLUSH>
    * f2 -> ( "(" VariableList() ")" )?
    * f3 -> OmpEol()
    */
   public void visit(OmpFlushDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <CANCEL>
    * f2 -> OmpConstructTypeClause()
    * f3 -> ( ( "," )? OmpIfClause() )?
    * f4 -> OmpEol()
    */
   public void visit(OmpCancelDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> <PARALLEL>
    *       | <SECTIONS>
    *       | <FOR>
    *       | <TASKGROUP>
    */
   public void visit(OmpConstructTypeClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpIfClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <CANCELLATION>
    * f2 -> <POINT>
    * f3 -> OmpConstructTypeClause()
    * f4 -> OmpEol()
    */
   public void visit(OmpCancellationPointDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> OmpDeclareTargetExtendedListDirective()
    *       | OmpDeclareTargetListDirective()
    *       | OmpDeclareTargetDirective()
    *       | OmpDeclareSimdDirective()
    *       | OmpThreadPrivateDirective()
    *       | OmpDeclareReductionDirective()
    */
   public void visit(OmpGlobalDirective n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> "("
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public void visit(OmpDeclareTargetExtendedListDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> OmpDeclareTargetClauseList()
    */
   public void visit(OmpDeclareTargetListDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpDeclareTargetClause()
    * f1 -> ( ( "," )? OmpDeclareTargetClause() )*
    */
   public void visit(OmpDeclareTargetClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpToClause()
    *       | OmpLinkClause()
    */
   public void visit(OmpDeclareTargetClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <LINK>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpLinkClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> OmpEol()
    * f4 -> ( FunctionDefinitionOrDeclaration() )*
    * f5 -> OmpPragma()
    * f6 -> <END>
    * f7 -> <DECLARE>
    * f8 -> <TARGET>
    */
   public void visit(OmpDeclareTargetDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> OmpDeclareSimdPragmaList()
    * f1 -> FunctionDefinitionOrDeclaration()
    */
   public void visit(OmpDeclareSimdDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpDeclareSimdPragma()
    * f1 -> ( OmpDeclareSimdPragma() )*
    */
   public void visit(OmpDeclareSimdPragmaList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <SIMD>
    * f3 -> ( OmpDeclareSimdClauseList() )?
    */
   public void visit(OmpDeclareSimdPragma n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OmpDeclareSimdClause()
    * f1 -> ( ( "," )? OmpDeclareSimdClause() )*
    */
   public void visit(OmpDeclareSimdClauseList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> OmpSimdLenClause()
    *       | OmpLinearClause()
    *       | OmpAlignedClause()
    *       | OmpUniformClause()
    *       | OmpInbranchClause()
    *       | OmpNotinbranchClause()
    */
   public void visit(OmpDeclareSimdClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <UNIFORM>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpUniformClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <INBRANCH>
    */
   public void visit(OmpInbranchClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <NOTINBRANCH>
    */
   public void visit(OmpNotinbranchClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Declaration()
    *       | FunctionDefinition()
    */
   public void visit(FunctionDefinitionOrDeclaration n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <THREADPRIVATE>
    * f2 -> "("
    * f3 -> VariableList()
    * f4 -> ")"
    * f5 -> OmpEol()
    */
   public void visit(OmpThreadPrivateDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <REDUCTION>
    * f3 -> "("
    * f4 -> ReductionOp()
    * f5 -> ":"
    * f6 -> ReductionTypeList()
    * f7 -> ":"
    * f8 -> Expression()
    * f9 -> ")"
    * f10 -> ( InitializerClause() )?
    * f11 -> OmpEol()
    */
   public void visit(OmpDeclareReductionDirective n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
   }

   /**
    * f0 -> ( TypeSpecifier() )*
    */
   public void visit(ReductionTypeList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> AssignInitializerClause()
    *       | ArgumentInitializerClause()
    */
   public void visit(InitializerClause n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INITIALIZER>
    * f1 -> "("
    * f2 -> <IDENTIFIER>
    * f3 -> "="
    * f4 -> Initializer()
    * f5 -> ")"
    */
   public void visit(AssignInitializerClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> <INITIALIZER>
    * f1 -> "("
    * f2 -> <IDENTIFIER>
    * f3 -> "("
    * f4 -> ExpressionList()
    * f5 -> ")"
    * f6 -> ")"
    */
   public void visit(ArgumentInitializerClause n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    *       | "+"
    *       | "*"
    *       | "-"
    *       | "&"
    *       | "^"
    *       | "|"
    *       | "||"
    *       | "&&"
    */
   public void visit(ReductionOp n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public void visit(VariableList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public void visit(Expression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> NonConditionalExpression()
    *       | ConditionalExpression()
    */
   public void visit(AssignmentExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> UnaryExpression()
    * f1 -> AssignmentOperator()
    * f2 -> AssignmentExpression()
    */
   public void visit(NonConditionalExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "="
    *       | "*="
    *       | "/="
    *       | "%="
    *       | "+="
    *       | "-="
    *       | "<<="
    *       | ">>="
    *       | "&="
    *       | "^="
    *       | "|="
    */
   public void visit(AssignmentOperator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> LogicalORExpression()
    * f1 -> ( "?" Expression() ":" ConditionalExpression() )?
    */
   public void visit(ConditionalExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ConditionalExpression()
    */
   public void visit(ConstantExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> ( "||" LogicalORExpression() )?
    */
   public void visit(LogicalORExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> ( "&&" LogicalANDExpression() )?
    */
   public void visit(LogicalANDExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> ( "|" InclusiveORExpression() )?
    */
   public void visit(InclusiveORExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ANDExpression()
    * f1 -> ( "^" ExclusiveORExpression() )?
    */
   public void visit(ExclusiveORExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> EqualityExpression()
    * f1 -> ( "&" ANDExpression() )?
    */
   public void visit(ANDExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> RelationalExpression()
    * f1 -> ( EqualOptionalExpression() )?
    */
   public void visit(EqualityExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> EqualExpression()
    *       | NonEqualExpression()
    */
   public void visit(EqualOptionalExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "=="
    * f1 -> EqualityExpression()
    */
   public void visit(EqualExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "!="
    * f1 -> EqualityExpression()
    */
   public void visit(NonEqualExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ShiftExpression()
    * f1 -> ( RelationalOptionalExpression() )?
    */
   public void visit(RelationalExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> RelationalLTExpression()
    *       | RelationalGTExpression()
    *       | RelationalLEExpression()
    *       | RelationalGEExpression()
    */
   public void visit(RelationalOptionalExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "<"
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalLTExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ">"
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalGTExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "<="
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalLEExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ">="
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalGEExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AdditiveExpression()
    * f1 -> ( ShiftOptionalExpression() )?
    */
   public void visit(ShiftExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ShiftLeftExpression()
    *       | ShiftRightExpression()
    */
   public void visit(ShiftOptionalExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ">>"
    * f1 -> ShiftExpression()
    */
   public void visit(ShiftLeftExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ShiftExpression()
    */
   public void visit(ShiftRightExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> ( AdditiveOptionalExpression() )?
    */
   public void visit(AdditiveExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> AdditivePlusExpression()
    *       | AdditiveMinusExpression()
    */
   public void visit(AdditiveOptionalExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "+"
    * f1 -> AdditiveExpression()
    */
   public void visit(AdditivePlusExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "-"
    * f1 -> AdditiveExpression()
    */
   public void visit(AdditiveMinusExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> CastExpression()
    * f1 -> ( MultiplicativeOptionalExpression() )?
    */
   public void visit(MultiplicativeExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> MultiplicativeMultiExpression()
    *       | MultiplicativeDivExpression()
    *       | MultiplicativeModExpression()
    */
   public void visit(MultiplicativeOptionalExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "*"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeMultiExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "/"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeDivExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "%"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeModExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> CastExpressionTyped()
    *       | UnaryExpression()
    */
   public void visit(CastExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> TypeName()
    * f2 -> ")"
    * f3 -> CastExpression()
    */
   public void visit(CastExpressionTyped n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> UnaryExpressionPreIncrement()
    *       | UnaryExpressionPreDecrement()
    *       | UnarySizeofExpression()
    *       | UnaryCastExpression()
    *       | PostfixExpression()
    */
   public void visit(UnaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "++"
    * f1 -> UnaryExpression()
    */
   public void visit(UnaryExpressionPreIncrement n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "--"
    * f1 -> UnaryExpression()
    */
   public void visit(UnaryExpressionPreDecrement n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> UnaryOperator()
    * f1 -> CastExpression()
    */
   public void visit(UnaryCastExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> SizeofTypeName()
    *       | SizeofUnaryExpression()
    */
   public void visit(UnarySizeofExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <SIZEOF>
    * f1 -> UnaryExpression()
    */
   public void visit(SizeofUnaryExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <SIZEOF>
    * f1 -> "("
    * f2 -> TypeName()
    * f3 -> ")"
    */
   public void visit(SizeofTypeName n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "&"
    *       | "*"
    *       | "+"
    *       | "-"
    *       | "~"
    *       | "!"
    */
   public void visit(UnaryOperator n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> PostfixOperationsList()
    */
   public void visit(PostfixExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( APostfixOperation() )*
    */
   public void visit(PostfixOperationsList n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> BracketExpression()
    *       | ArgumentList()
    *       | DotId()
    *       | ArrowId()
    *       | PlusPlus()
    *       | MinusMinus()
    */
   public void visit(APostfixOperation n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "++"
    */
   public void visit(PlusPlus n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "--"
    */
   public void visit(MinusMinus n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "["
    * f1 -> Expression()
    * f2 -> "]"
    */
   public void visit(BracketExpression n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> ( ExpressionList() )?
    * f2 -> ")"
    */
   public void visit(ArgumentList n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "."
    * f1 -> <IDENTIFIER>
    */
   public void visit(DotId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "->"
    * f1 -> <IDENTIFIER>
    */
   public void visit(ArrowId n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    *       | Constant()
    *       | ExpressionClosed()
    *       | GenericSelection()
    */
   public void visit(PrimaryExpression n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public void visit(ExpressionClosed n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public void visit(ExpressionList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | ( <STRING_LITERAL> )+
    */
   public void visit(Constant n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <_GENERIC>
    * f1 -> "("
    * f2 -> AssignmentExpression()
    * f3 -> ","
    * f4 -> GenericAssocList()
    * f5 -> ")"
    */
   public void visit(GenericSelection n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> GenericAssociation()
    * f1 -> ( "," GenericAssociation() )*
    */
   public void visit(GenericAssocList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> TypeName() ":" AssignmentExpression()
    *       | <DFLT> ":" AssignmentExpression()
    */
   public void visit(GenericAssociation n) {
      n.f0.accept(this);
   }

}
