//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ElementsOfTranslation() )+
    */
   public R visit(TranslationUnit n, A argu);

   /**
    * f0 -> ExternalDeclaration()
    *       | UnknownCpp()
    *       | UnknownPragma()
    */
   public R visit(ElementsOfTranslation n, A argu);

   /**
    * f0 -> Declaration()
    *       | FunctionDefinition()
    *       | OmpGlobalDirective()
    */
   public R visit(ExternalDeclaration n, A argu);

   /**
    * f0 -> ( DeclarationSpecifiers() )?
    * f1 -> Declarator()
    * f2 -> ( DeclarationList() )?
    * f3 -> CompoundStatement()
    */
   public R visit(FunctionDefinition n, A argu);

   /**
    * f0 -> DeclarationSpecifiers() ( InitDeclaratorList() )? ";"
    *       | StaticAssertDeclaration()
    */
   public R visit(Declaration n, A argu);

   /**
    * f0 -> <STATIC_ASSERT>
    * f1 -> "("
    * f2 -> ConstantExpression()
    * f3 -> ","
    * f4 -> <STRING_LITERAL>
    * f5 -> ")"
    */
   public R visit(StaticAssertDeclaration n, A argu);

   /**
    * f0 -> ( Declaration() )+
    */
   public R visit(DeclarationList n, A argu);

   /**
    * f0 -> ( ADeclarationSpecifier() )+
    */
   public R visit(DeclarationSpecifiers n, A argu);

   /**
    * f0 -> StorageClassSpecifier()
    *       | TypeSpecifier()
    *       | TypeQualifier()
    *       | FunctionSpecifier()
    *       | AlignmentSpecifier()
    */
   public R visit(ADeclarationSpecifier n, A argu);

   /**
    * f0 -> <INLINE>
    *       | <NORETURN>
    */
   public R visit(FunctionSpecifier n, A argu);

   /**
    * f0 -> AlignAsTypeName()
    *       | AlignAsConstantExpression()
    */
   public R visit(AlignmentSpecifier n, A argu);

   /**
    * f0 -> <ALIGNAS>
    * f1 -> "("
    * f2 -> TypeName()
    * f3 -> ")"
    */
   public R visit(AlignAsTypeName n, A argu);

   /**
    * f0 -> <ALIGNAS>
    * f1 -> "("
    * f2 -> ConstantExpression()
    * f3 -> ")"
    */
   public R visit(AlignAsConstantExpression n, A argu);

   /**
    * f0 -> <AUTO>
    *       | <REGISTER>
    *       | <STATIC>
    *       | <EXTERN>
    *       | <TYPEDEF>
    */
   public R visit(StorageClassSpecifier n, A argu);

   /**
    * f0 -> ( <VOID> | <CHAR> | <SHORT> | <INT> | <LONG> | <FLOAT> | <DOUBLE> | <SIGNED> | <UNSIGNED> | StructOrUnionSpecifier() | EnumSpecifier() | TypedefName() )
    */
   public R visit(TypeSpecifier n, A argu);

   /**
    * f0 -> <RESTRICT>
    *       | <CONST>
    *       | <VOLATILE>
    *       | <CCONST>
    *       | <CSIGNED>
    *       | <CSIGNED2>
    */
   public R visit(TypeQualifier n, A argu);

   /**

    * f0 -> ( StructOrUnionSpecifierWithList() | StructOrUnionSpecifierWithId() )
    */
   public R visit(StructOrUnionSpecifier n, A argu);

   /**
    * f0 -> StructOrUnion()
    * f1 -> ( <IDENTIFIER> )?
    * f2 -> "{"
    * f3 -> StructDeclarationList()
    * f4 -> "}"
    */
   public R visit(StructOrUnionSpecifierWithList n, A argu);

   /**
    * f0 -> StructOrUnion()
    * f1 -> <IDENTIFIER>
    */
   public R visit(StructOrUnionSpecifierWithId n, A argu);

   /**
    * f0 -> <STRUCT>
    *       | <UNION>
    */
   public R visit(StructOrUnion n, A argu);

   /**
    * f0 -> ( StructDeclaration() )+
    */
   public R visit(StructDeclarationList n, A argu);

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( "," InitDeclarator() )*
    */
   public R visit(InitDeclaratorList n, A argu);

   /**
    * f0 -> Declarator()
    * f1 -> ( "=" Initializer() )?
    */
   public R visit(InitDeclarator n, A argu);

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> StructDeclaratorList()
    * f2 -> ";"
    */
   public R visit(StructDeclaration n, A argu);

   /**
    * f0 -> ( ASpecifierQualifier() )+
    */
   public R visit(SpecifierQualifierList n, A argu);

   /**
    * f0 -> TypeSpecifier()
    *       | TypeQualifier()
    */
   public R visit(ASpecifierQualifier n, A argu);

   /**
    * f0 -> StructDeclarator()
    * f1 -> ( "," StructDeclarator() )*
    */
   public R visit(StructDeclaratorList n, A argu);

   /**
    * f0 -> StructDeclaratorWithDeclarator()
    *       | StructDeclaratorWithBitField()
    */
   public R visit(StructDeclarator n, A argu);

   /**
    * f0 -> Declarator()
    * f1 -> ( ":" ConstantExpression() )?
    */
   public R visit(StructDeclaratorWithDeclarator n, A argu);

   /**
    * f0 -> ":"
    * f1 -> ConstantExpression()
    */
   public R visit(StructDeclaratorWithBitField n, A argu);

   /**
    * f0 -> EnumSpecifierWithList()
    *       | EnumSpecifierWithId()
    */
   public R visit(EnumSpecifier n, A argu);

   /**
    * f0 -> <ENUM>
    * f1 -> ( <IDENTIFIER> )?
    * f2 -> "{"
    * f3 -> EnumeratorList()
    * f4 -> "}"
    */
   public R visit(EnumSpecifierWithList n, A argu);

   /**
    * f0 -> <ENUM>
    * f1 -> <IDENTIFIER>
    */
   public R visit(EnumSpecifierWithId n, A argu);

   /**
    * f0 -> Enumerator()
    * f1 -> ( "," Enumerator() )*
    */
   public R visit(EnumeratorList n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "=" ConstantExpression() )?
    */
   public R visit(Enumerator n, A argu);

   /**
    * f0 -> ( Pointer() )?
    * f1 -> DirectDeclarator()
    */
   public R visit(Declarator n, A argu);

   /**
    * f0 -> IdentifierOrDeclarator()
    * f1 -> DeclaratorOpList()
    */
   public R visit(DirectDeclarator n, A argu);

   /**
    * f0 -> ( ADeclaratorOp() )*
    */
   public R visit(DeclaratorOpList n, A argu);

   /**
    * f0 -> DimensionSize()
    *       | ParameterTypeListClosed()
    *       | OldParameterListClosed()
    */
   public R visit(ADeclaratorOp n, A argu);

   /**
    * f0 -> "["
    * f1 -> ( ConstantExpression() )?
    * f2 -> "]"
    */
   public R visit(DimensionSize n, A argu);

   /**
    * f0 -> "("
    * f1 -> ( ParameterTypeList() )?
    * f2 -> ")"
    */
   public R visit(ParameterTypeListClosed n, A argu);

   /**
    * f0 -> "("
    * f1 -> ( OldParameterList() )?
    * f2 -> ")"
    */
   public R visit(OldParameterListClosed n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    *       | "(" Declarator() ")"
    */
   public R visit(IdentifierOrDeclarator n, A argu);

   /**
    * f0 -> ( "*" | "^" )
    * f1 -> ( TypeQualifierList() )?
    * f2 -> ( Pointer() )?
    */
   public R visit(Pointer n, A argu);

   /**
    * f0 -> ( TypeQualifier() )+
    */
   public R visit(TypeQualifierList n, A argu);

   /**
    * f0 -> ParameterList()
    * f1 -> ( "," "..." )?
    */
   public R visit(ParameterTypeList n, A argu);

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public R visit(ParameterList n, A argu);

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ParameterAbstraction()
    */
   public R visit(ParameterDeclaration n, A argu);

   /**
    * f0 -> Declarator()
    *       | AbstractOptionalDeclarator()
    */
   public R visit(ParameterAbstraction n, A argu);

   /**
    * f0 -> ( AbstractDeclarator() )?
    */
   public R visit(AbstractOptionalDeclarator n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public R visit(OldParameterList n, A argu);

   /**
    * f0 -> AssignmentExpression()
    *       | ArrayInitializer()
    */
   public R visit(Initializer n, A argu);

   /**
    * f0 -> "{"
    * f1 -> InitializerList()
    * f2 -> ( "," )?
    * f3 -> "}"
    */
   public R visit(ArrayInitializer n, A argu);

   /**
    * f0 -> Initializer()
    * f1 -> ( "," Initializer() )*
    */
   public R visit(InitializerList n, A argu);

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> ( AbstractDeclarator() )?
    */
   public R visit(TypeName n, A argu);

   /**
    * f0 -> AbstractDeclaratorWithPointer()
    *       | DirectAbstractDeclarator()
    */
   public R visit(AbstractDeclarator n, A argu);

   /**
    * f0 -> Pointer()
    * f1 -> ( DirectAbstractDeclarator() )?
    */
   public R visit(AbstractDeclaratorWithPointer n, A argu);

   /**
    * f0 -> AbstractDimensionOrParameter()
    * f1 -> DimensionOrParameterList()
    */
   public R visit(DirectAbstractDeclarator n, A argu);

   /**
    * f0 -> AbstractDeclaratorClosed()
    *       | DimensionSize()
    *       | ParameterTypeListClosed()
    */
   public R visit(AbstractDimensionOrParameter n, A argu);

   /**
    * f0 -> "("
    * f1 -> AbstractDeclarator()
    * f2 -> ")"
    */
   public R visit(AbstractDeclaratorClosed n, A argu);

   /**
    * f0 -> ( ADimensionOrParameter() )*
    */
   public R visit(DimensionOrParameterList n, A argu);

   /**
    * f0 -> DimensionSize()
    *       | ParameterTypeListClosed()
    */
   public R visit(ADimensionOrParameter n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(TypedefName n, A argu);

   /**
    * f0 -> LabeledStatement()
    *       | ExpressionStatement()
    *       | CompoundStatement()
    *       | SelectionStatement()
    *       | IterationStatement()
    *       | JumpStatement()
    *       | UnknownPragma()
    *       | OmpConstruct()
    *       | OmpDirective()
    *       | UnknownCpp()
    */
   public R visit(Statement n, A argu);

   /**
    * f0 -> SimpleLabeledStatement()
    *       | CaseLabeledStatement()
    *       | DefaultLabeledStatement()
    */
   public R visit(LabeledStatement n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public R visit(SimpleLabeledStatement n, A argu);

   /**
    * f0 -> <CASE>
    * f1 -> ConstantExpression()
    * f2 -> ":"
    * f3 -> Statement()
    */
   public R visit(CaseLabeledStatement n, A argu);

   /**
    * f0 -> <DFLT>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public R visit(DefaultLabeledStatement n, A argu);

   /**
    * f0 -> ( Expression() )?
    * f1 -> ";"
    */
   public R visit(ExpressionStatement n, A argu);

   /**
    * f0 -> "{"
    * f1 -> ( CompoundStatementElement() )*
    * f2 -> "}"
    */
   public R visit(CompoundStatement n, A argu);

   /**
    * f0 -> Declaration()
    *       | Statement()
    */
   public R visit(CompoundStatementElement n, A argu);

   /**
    * f0 -> IfStatement()
    *       | SwitchStatement()
    */
   public R visit(SelectionStatement n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> ( <ELSE> Statement() )?
    */
   public R visit(IfStatement n, A argu);

   /**
    * f0 -> <SWITCH>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(SwitchStatement n, A argu);

   /**
    * f0 -> WhileStatement()
    *       | DoStatement()
    *       | ForStatement()
    */
   public R visit(IterationStatement n, A argu);

   /**
    * f0 -> <WHILE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu);

   /**
    * f0 -> <DO>
    * f1 -> Statement()
    * f2 -> <WHILE>
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public R visit(DoStatement n, A argu);

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> ( Expression() )?
    * f3 -> ";"
    * f4 -> ( Expression() )?
    * f5 -> ";"
    * f6 -> ( Expression() )?
    * f7 -> ")"
    * f8 -> Statement()
    */
   public R visit(ForStatement n, A argu);

   /**
    * f0 -> GotoStatement()
    *       | ContinueStatement()
    *       | BreakStatement()
    *       | ReturnStatement()
    */
   public R visit(JumpStatement n, A argu);

   /**
    * f0 -> <GOTO>
    * f1 -> <IDENTIFIER>
    * f2 -> ";"
    */
   public R visit(GotoStatement n, A argu);

   /**
    * f0 -> <CONTINUE>
    * f1 -> ";"
    */
   public R visit(ContinueStatement n, A argu);

   /**
    * f0 -> <BREAK>
    * f1 -> ";"
    */
   public R visit(BreakStatement n, A argu);

   /**
    * f0 -> <RETURN>
    * f1 -> ( Expression() )?
    * f2 -> ";"
    */
   public R visit(ReturnStatement n, A argu);

   /**
    * f0 -> "#"
    * f1 -> <UNKNOWN_CPP>
    */
   public R visit(UnknownCpp n, A argu);

   /**
    * f0 -> <OMP_CR>
    *       | <OMP_NL>
    */
   public R visit(OmpEol n, A argu);

   /**
    * f0 -> OmpParallelConstruct()
    *       | OmpForConstruct()
    *       | OmpSectionsConstruct()
    *       | OmpSingleConstruct()
    *       | OmpSimdConstruct()
    *       | OmpForSimdConstruct()
    *       | OmpTaskConstruct()
    *       | OmpTaskLoopSimdConstruct()
    *       | OmpTaskLoopConstruct()
    *       | OmpTargetDataConstruct()
    *       | OmpTargetParallelForSimdConstruct()
    *       | OmpTargetParallelForConstruct()
    *       | OmpTargetParallelConstruct()
    *       | OmpTargetSimdConstruct()
    *       | OmpTargetTeamsDistributeParallelForSimdConstruct()
    *       | OmpTargetTeamsDistributeParallelForConstruct()
    *       | OmpTargetTeamsDistributeSimdConstruct()
    *       | OmpTargetTeamsDistributeConstruct()
    *       | OmpTargetTeamsConstruct()
    *       | OmpTargetConstruct()
    *       | OmpTeamsDistributeParallelForSimdConstruct()
    *       | OmpTeamsDistributeParallelForConstruct()
    *       | OmpTeamsDistributeSimdConstruct()
    *       | OmpTeamsDistributeConstruct()
    *       | OmpTeamsConstruct()
    *       | OmpDistributeSimdConstruct()
    *       | OmpDistributeParallelForSimdConstruct()
    *       | OmpDistributeParallelForConstruct()
    *       | OmpDistributeConstruct()
    *       | OmpParallelForSimdConstruct()
    *       | OmpParallelForConstruct()
    *       | OmpParallelSectionsConstruct()
    *       | OmpMasterConstruct()
    *       | OmpCriticalConstruct()
    *       | OmpTaskGroupConstruct()
    *       | OmpAtomicConstruct()
    *       | OmpOrderedConstruct()
    */
   public R visit(OmpConstruct n, A argu);

   /**
    * f0 -> OmpTaskyieldDirective()
    *       | OmpTargetEnterDataDirective()
    *       | OmpTargetExitDataDirective()
    *       | OmpTargetUpdateDirective()
    *       | OmpBarrierDirective()
    *       | OmpTaskwaitDirective()
    *       | OmpFlushDirective()
    *       | OmpCancelDirective()
    *       | OmpCancellationPointDirective()
    */
   public R visit(OmpDirective n, A argu);

   /**
    * f0 -> "#"
    * f1 -> <PRAGMA>
    * f2 -> <OMP>
    */
   public R visit(OmpPragma n, A argu);

   /**
    * f0 -> "#"
    * f1 -> <PRAGMA>
    * f2 -> <UNKNOWN_CPP>
    */
   public R visit(UnknownPragma n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> ( OmpParallelClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpParallelConstruct n, A argu);

   /**
    * f0 -> OmpParallelClause()
    * f1 -> ( ( "," )? OmpParallelClause() )*
    */
   public R visit(OmpParallelClauseList n, A argu);

   /**
    * f0 -> OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpCopyinClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    */
   public R visit(OmpParallelClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <PARALLEL> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfParallelClause n, A argu);

   /**
    * f0 -> <NUM_THREADS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpNumThreadsClause n, A argu);

   /**
    * f0 -> <DFLT>
    * f1 -> "("
    * f2 -> <SHARED>
    * f3 -> ")"
    */
   public R visit(OmpDfltSharedClause n, A argu);

   /**
    * f0 -> <DFLT>
    * f1 -> "("
    * f2 -> <NONE>
    * f3 -> ")"
    */
   public R visit(OmpDfltNoneClause n, A argu);

   /**
    * f0 -> <PRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpPrivateClause n, A argu);

   /**
    * f0 -> <FIRSTPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpFirstPrivateClause n, A argu);

   /**
    * f0 -> <SHARED>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpSharedClause n, A argu);

   /**
    * f0 -> <COPYIN>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpCopyinClause n, A argu);

   /**
    * f0 -> <REDUCTION>
    * f1 -> "("
    * f2 -> ReductionOp()
    * f3 -> ":"
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public R visit(OmpReductionClause n, A argu);

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <MASTER>
    * f3 -> ")"
    */
   public R visit(OmpThreadAffinityMasterClause n, A argu);

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <CLOSE>
    * f3 -> ")"
    */
   public R visit(OmpThreadAffinityCloseClause n, A argu);

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <SPREAD>
    * f3 -> ")"
    */
   public R visit(OmpThreadAffinitySpreadClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <FOR>
    * f2 -> ( OmpForClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public R visit(OmpForConstruct n, A argu);

   /**
    * f0 -> OmpForClause()
    * f1 -> ( ( "," )? OmpForClause() )*
    */
   public R visit(OmpForClauseList n, A argu);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpReductionClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    *       | OmpNowaitClause()
    */
   public R visit(OmpForClause n, A argu);

   /**
    * f0 -> <LASTPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpLastPrivateClause n, A argu);

   /**
    * f0 -> <LINEAR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ( <COLON> Expression() )?
    * f4 -> ")"
    */
   public R visit(OmpLinearClause n, A argu);

   /**
    * f0 -> <SCHEDULE>
    * f1 -> "("
    * f2 -> ( Modifier() ( "," Modifier() )? <COLON> )?
    * f3 -> ScheduleKind()
    * f4 -> ( "," Expression() )?
    * f5 -> ")"
    */
   public R visit(OmpScheduleClause n, A argu);

   /**
    * f0 -> <MONOTONIC>
    *       | <NONMONOTONIC>
    *       | <SIMD>
    */
   public R visit(Modifier n, A argu);

   /**
    * f0 -> <STATIC>
    *       | <DYNAMIC>
    *       | <GUIDED>
    *       | <RUNTIME>
    *       | <AUTO>
    */
   public R visit(ScheduleKind n, A argu);

   /**
    * f0 -> <COLLAPSE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpCollapseClause n, A argu);

   /**
    * f0 -> <ORDERED>
    * f1 -> ( "(" Expression() ")" )?
    */
   public R visit(OmpOrderedClause n, A argu);

   /**
    * f0 -> <NOWAIT>
    */
   public R visit(OmpNowaitClause n, A argu);

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> OmpForInitExpression()
    * f3 -> ";"
    * f4 -> OmpForCondition()
    * f5 -> ";"
    * f6 -> OmpForReinitExpression()
    * f7 -> ")"
    */
   public R visit(OmpForHeader n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> Expression()
    */
   public R visit(OmpForInitExpression n, A argu);

   /**
    * f0 -> OmpForLTCondition()
    *       | OmpForLECondition()
    *       | OmpForGTCondition()
    *       | OmpForGECondition()
    */
   public R visit(OmpForCondition n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "<"
    * f2 -> Expression()
    */
   public R visit(OmpForLTCondition n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "<="
    * f2 -> Expression()
    */
   public R visit(OmpForLECondition n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ">"
    * f2 -> Expression()
    */
   public R visit(OmpForGTCondition n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ">="
    * f2 -> Expression()
    */
   public R visit(OmpForGECondition n, A argu);

   /**
    * f0 -> PostIncrementId()
    *       | PostDecrementId()
    *       | PreIncrementId()
    *       | PreDecrementId()
    *       | ShortAssignPlus()
    *       | ShortAssignMinus()
    *       | OmpForAdditive()
    *       | OmpForSubtractive()
    *       | OmpForMultiplicative()
    */
   public R visit(OmpForReinitExpression n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "++"
    */
   public R visit(PostIncrementId n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "--"
    */
   public R visit(PostDecrementId n, A argu);

   /**
    * f0 -> "++"
    * f1 -> <IDENTIFIER>
    */
   public R visit(PreIncrementId n, A argu);

   /**
    * f0 -> "--"
    * f1 -> <IDENTIFIER>
    */
   public R visit(PreDecrementId n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "+="
    * f2 -> Expression()
    */
   public R visit(ShortAssignPlus n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "-="
    * f2 -> Expression()
    */
   public R visit(ShortAssignMinus n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> <IDENTIFIER>
    * f3 -> "+"
    * f4 -> AdditiveExpression()
    */
   public R visit(OmpForAdditive n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> <IDENTIFIER>
    * f3 -> "-"
    * f4 -> AdditiveExpression()
    */
   public R visit(OmpForSubtractive n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> MultiplicativeExpression()
    * f3 -> "+"
    * f4 -> <IDENTIFIER>
    */
   public R visit(OmpForMultiplicative n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SECTIONS>
    * f2 -> ( OmpSectionsClauseList() )?
    * f3 -> OmpEol()
    * f4 -> SectionsScope()
    */
   public R visit(OmpSectionsConstruct n, A argu);

   /**
    * f0 -> OmpSectionsClause()
    * f1 -> ( ( "," )? OmpSectionsClause() )*
    */
   public R visit(OmpSectionsClauseList n, A argu);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpReductionClause()
    *       | OmpNowaitClause()
    */
   public R visit(OmpSectionsClause n, A argu);

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )?
    * f2 -> ( ASection() )*
    * f3 -> "}"
    */
   public R visit(SectionsScope n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SECTION>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public R visit(ASection n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SINGLE>
    * f2 -> ( OmpSingleClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpSingleConstruct n, A argu);

   /**
    * f0 -> OmpSingleClause()
    * f1 -> ( OmpSingleClause() )*
    */
   public R visit(OmpSingleClauseList n, A argu);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpCopyPrivateClause()
    *       | OmpNowaitClause()
    */
   public R visit(OmpSingleClause n, A argu);

   /**
    * f0 -> <COPYPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpCopyPrivateClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SIMD>
    * f2 -> ( OmpSimdClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public R visit(OmpSimdConstruct n, A argu);

   /**
    * f0 -> OmpSimdClause()
    * f1 -> ( ( "," )? OmpSimdClause() )*
    */
   public R visit(OmpSimdClauseList n, A argu);

   /**
    * f0 -> OmpSafeLenClause()
    *       | OmpSimdLenClause()
    *       | OmpLinearClause()
    *       | OmpAlignedClause()
    *       | OmpPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpReductionClause()
    *       | OmpCollapseClause()
    */
   public R visit(OmpSimdClause n, A argu);

   /**
    * f0 -> <SAFELEN>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpSafeLenClause n, A argu);

   /**
    * f0 -> <SIMDLEN>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpSimdLenClause n, A argu);

   /**
    * f0 -> <ALIGNED>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ( <COLON> Expression() )?
    * f4 -> ")"
    */
   public R visit(OmpAlignedClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <FOR>
    * f2 -> <SIMD>
    * f3 -> ( OmpForSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public R visit(OmpForSimdConstruct n, A argu);

   /**
    * f0 -> OmpForSimdClause()
    * f1 -> ( ( "," )? OmpForSimdClause() )*
    */
   public R visit(OmpForSimdClauseList n, A argu);

   /**
    * f0 -> OmpSimdClause()
    *       | OmpForClause()
    */
   public R visit(OmpForSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASK>
    * f2 -> ( TaskClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpTaskConstruct n, A argu);

   /**
    * f0 -> TaskClause()
    * f1 -> ( ( "," )? TaskClause() )*
    */
   public R visit(TaskClauseList n, A argu);

   /**
    * f0 -> OmpIfTaskClause()
    *       | OmpFinalClause()
    *       | OmpUntiedClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpMergeableClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpDependClause()
    *       | OmpPriorityClause()
    */
   public R visit(TaskClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TASK> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfTaskClause n, A argu);

   /**
    * f0 -> <FINAL>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpFinalClause n, A argu);

   /**
    * f0 -> <UNTIED>
    */
   public R visit(OmpUntiedClause n, A argu);

   /**
    * f0 -> <MERGEABLE>
    */
   public R visit(OmpMergeableClause n, A argu);

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> DependencyType()
    * f3 -> <COLON>
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public R visit(OmpDependClause n, A argu);

   /**
    * f0 -> <IN>
    *       | <OUT>
    *       | <INOUT>
    */
   public R visit(DependencyType n, A argu);

   /**
    * f0 -> <PRIORITY>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpPriorityClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKLOOP>
    * f2 -> <SIMD>
    * f3 -> ( OmpTaskLoopSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public R visit(OmpTaskLoopSimdConstruct n, A argu);

   /**
    * f0 -> OmpTaskLoopSimdClause()
    * f1 -> ( ( "," )? OmpTaskLoopSimdClause() )*
    */
   public R visit(OmpTaskLoopSimdClauseList n, A argu);

   /**
    * f0 -> OmpSimdClause()
    *       | OmpTaskLoopClause()
    */
   public R visit(OmpTaskLoopSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKLOOP>
    * f2 -> ( OmpTaskLoopClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public R visit(OmpTaskLoopConstruct n, A argu);

   /**
    * f0 -> OmpTaskLoopClause()
    * f1 -> ( ( "," )? OmpTaskLoopClause() )*
    */
   public R visit(OmpTaskLoopClauseList n, A argu);

   /**
    * f0 -> OmpIfTaskLoopClause()
    *       | OmpSharedClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpGrainSizeClause()
    *       | OmpNumTasksClause()
    *       | OmpCollapseClause()
    *       | OmpFinalClause()
    *       | OmpPriorityClause()
    *       | OmpUntiedClause()
    *       | OmpMergeableClause()
    *       | OmpNoGroupClause()
    */
   public R visit(OmpTaskLoopClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TASKLOOP> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfTaskLoopClause n, A argu);

   /**
    * f0 -> <GRAINSIZE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpGrainSizeClause n, A argu);

   /**
    * f0 -> <NUMTASKS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpNumTasksClause n, A argu);

   /**
    * f0 -> <NOGROUP>
    */
   public R visit(OmpNoGroupClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <DATA>
    * f3 -> ( OmpTargetDataClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public R visit(OmpTargetDataConstruct n, A argu);

   /**
    * f0 -> OmpTargetDataClause()
    * f1 -> ( ( "," )? OmpTargetDataClause() )*
    */
   public R visit(OmpTargetDataClauseList n, A argu);

   /**
    * f0 -> OmpIfTargetDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpUseDevicePtrClause()
    */
   public R visit(OmpTargetDataClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> <TARGET>
    * f3 -> <DATA>
    * f4 -> Expression()
    * f5 -> ")"
    */
   public R visit(OmpIfTargetDataClause n, A argu);

   /**
    * f0 -> <USEDEVICEPTR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpUseDevicePtrClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> <SIMD>
    * f5 -> ( OmpTargetParallelForSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public R visit(OmpTargetParallelForSimdConstruct n, A argu);

   /**
    * f0 -> OmpTargetParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTargetParallelForSimdClause() )*
    */
   public R visit(OmpTargetParallelForSimdClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpSimdClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public R visit(OmpTargetParallelForSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> ( OmpTargetParallelForClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public R visit(OmpTargetParallelForConstruct n, A argu);

   /**
    * f0 -> OmpTargetParallelForClause()
    * f1 -> ( ( "," )? OmpTargetParallelForClause() )*
    */
   public R visit(OmpTargetParallelForClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public R visit(OmpTargetParallelForClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> ( OmpTargetParallelClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public R visit(OmpTargetParallelConstruct n, A argu);

   /**
    * f0 -> OmpTargetParallelClause()
    * f1 -> ( ( "," )? OmpTargetParallelClause() )*
    */
   public R visit(OmpTargetParallelClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    */
   public R visit(OmpTargetParallelClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <SIMD>
    * f3 -> ( OmpTargetSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public R visit(OmpTargetSimdConstruct n, A argu);

   /**
    * f0 -> OmpTargetSimdClause()
    * f1 -> ( ( "," )? OmpTargetSimdClause() )*
    */
   public R visit(OmpTargetSimdClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpSimdClause()
    */
   public R visit(OmpTargetSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> <SIMD>
    * f6 -> ( OmpTargetTeamsDistributeParallelForSimdClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public R visit(OmpTargetTeamsDistributeParallelForSimdConstruct n, A argu);

   /**
    * f0 -> OmpTargetTeamsDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeParallelForSimdClause() )*
    */
   public R visit(OmpTargetTeamsDistributeParallelForSimdClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeParallelForSimdClause()
    */
   public R visit(OmpTargetTeamsDistributeParallelForSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> <PARALLEL>
    * f5 -> <FOR>
    * f6 -> ( OmpTargetTeamsDistributeParallelForClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public R visit(OmpTargetTeamsDistributeParallelForConstruct n, A argu);

   /**
    * f0 -> OmpTargetTeamsDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeParallelForClause() )*
    */
   public R visit(OmpTargetTeamsDistributeParallelForClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeParallelForClause()
    */
   public R visit(OmpTargetTeamsDistributeParallelForClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> <SIMD>
    * f5 -> ( OmpTargetTeamsDistributeSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public R visit(OmpTargetTeamsDistributeSimdConstruct n, A argu);

   /**
    * f0 -> OmpTargetTeamsDistributeSimdClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeSimdClause() )*
    */
   public R visit(OmpTargetTeamsDistributeSimdClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeSimdClause()
    */
   public R visit(OmpTargetTeamsDistributeSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> ( OmpTargetTeamsDistributeClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public R visit(OmpTargetTeamsDistributeConstruct n, A argu);

   /**
    * f0 -> OmpTargetTeamsDistributeClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeClause() )*
    */
   public R visit(OmpTargetTeamsDistributeClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeClause()
    */
   public R visit(OmpTargetTeamsDistributeClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> ( OmpTargetTeamsClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public R visit(OmpTargetTeamsConstruct n, A argu);

   /**
    * f0 -> OmpTargetTeamsClause()
    * f1 -> ( ( "," )? OmpTargetTeamsClause() )*
    */
   public R visit(OmpTargetTeamsClauseList n, A argu);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsClause()
    */
   public R visit(OmpTargetTeamsClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> ( OmpTargetClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpTargetConstruct n, A argu);

   /**
    * f0 -> OmpTargetClause()
    * f1 -> ( ( "," )? OmpTargetClause() )*
    */
   public R visit(OmpTargetClauseList n, A argu);

   /**
    * f0 -> OmpIfTargetClause()
    *       | OmpDeviceClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpMapClause()
    *       | OmpIsDevicePtrListClause()
    *       | OmpDefaultMapClause()
    *       | OmpNowaitClause()
    *       | OmpDependClause()
    */
   public R visit(OmpTargetClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfTargetClause n, A argu);

   /**
    * f0 -> <ISDEVICEPTR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpIsDevicePtrListClause n, A argu);

   /**
    * f0 -> <DEFAULTMAP>
    * f1 -> "("
    * f2 -> <TOFROM>
    * f3 -> <COLON>
    * f4 -> <SCALAR>
    * f5 -> ")"
    */
   public R visit(OmpDefaultMapClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> <SIMD>
    * f6 -> ( OmpTeamsDistributeParallelForSimdClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public R visit(OmpTeamsDistributeParallelForSimdConstruct n, A argu);

   /**
    * f0 -> OmpTeamsDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeParallelForSimdClause() )*
    */
   public R visit(OmpTeamsDistributeParallelForSimdClauseList n, A argu);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeParallelForSimdClause()
    */
   public R visit(OmpTeamsDistributeParallelForSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> ( OmpTeamsDistributeParallelForClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public R visit(OmpTeamsDistributeParallelForConstruct n, A argu);

   /**
    * f0 -> OmpTeamsDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeParallelForClause() )*
    */
   public R visit(OmpTeamsDistributeParallelForClauseList n, A argu);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeParallelForClause()
    */
   public R visit(OmpTeamsDistributeParallelForClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <SIMD>
    * f4 -> ( OmpTeamsDistributeSimdClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public R visit(OmpTeamsDistributeSimdConstruct n, A argu);

   /**
    * f0 -> OmpTeamsDistributeSimdClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeSimdClause() )*
    */
   public R visit(OmpTeamsDistributeSimdClauseList n, A argu);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeSimdClause()
    */
   public R visit(OmpTeamsDistributeSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> ( OmpTeamsDistributeClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public R visit(OmpTeamsDistributeConstruct n, A argu);

   /**
    * f0 -> OmpTeamsDistributeClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeClause() )*
    */
   public R visit(OmpTeamsDistributeClauseList n, A argu);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeClause()
    */
   public R visit(OmpTeamsDistributeClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> ( OmpTeamsClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpTeamsConstruct n, A argu);

   /**
    * f0 -> OmpTeamsClause()
    * f1 -> ( ( "," )? OmpTeamsClause() )*
    */
   public R visit(OmpTeamsClauseList n, A argu);

   /**
    * f0 -> OmpNumTeamsClause()
    *       | OmpThreadLimitClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    */
   public R visit(OmpTeamsClause n, A argu);

   /**
    * f0 -> <NUMTEAMS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpNumTeamsClause n, A argu);

   /**
    * f0 -> <THREADLIMIT>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpThreadLimitClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <SIMD>
    * f3 -> ( OmpDistributeSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public R visit(OmpDistributeSimdConstruct n, A argu);

   /**
    * f0 -> OmpDistributeSimdClause()
    * f1 -> ( ( "," )? OmpDistributeSimdClause() )*
    */
   public R visit(OmpDistributeSimdClauseList n, A argu);

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpSimdClause()
    */
   public R visit(OmpDistributeSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> <SIMD>
    * f5 -> ( OmpDistributeParallelForSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public R visit(OmpDistributeParallelForSimdConstruct n, A argu);

   /**
    * f0 -> OmpDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpDistributeParallelForSimdClause() )*
    */
   public R visit(OmpDistributeParallelForSimdClauseList n, A argu);

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpParallelForSimdClause()
    */
   public R visit(OmpDistributeParallelForSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> ( OmpDistributeParallelForClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public R visit(OmpDistributeParallelForConstruct n, A argu);

   /**
    * f0 -> OmpDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpDistributeParallelForClause() )*
    */
   public R visit(OmpDistributeParallelForClauseList n, A argu);

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpParallelForClause()
    */
   public R visit(OmpDistributeParallelForClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> ( OmpDistributeClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public R visit(OmpDistributeConstruct n, A argu);

   /**
    * f0 -> OmpDistributeClause()
    * f1 -> ( ( "," )? OmpDistributeClause() )*
    */
   public R visit(OmpDistributeClauseList n, A argu);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpCollapseClause()
    *       | OmpDistScheduleClause()
    */
   public R visit(OmpDistributeClause n, A argu);

   /**
    * f0 -> <DISTSCHEDULE>
    * f1 -> "("
    * f2 -> ScheduleKind()
    * f3 -> ( "," Expression() )?
    * f4 -> ")"
    */
   public R visit(OmpDistScheduleClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <FOR>
    * f3 -> <SIMD>
    * f4 -> ( OmpParallelForSimdClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public R visit(OmpParallelForSimdConstruct n, A argu);

   /**
    * f0 -> OmpParallelForSimdClause()
    * f1 -> ( ( "," )? OmpParallelForSimdClause() )*
    */
   public R visit(OmpParallelForSimdClauseList n, A argu);

   /**
    * f0 -> OmpParallelClause()
    *       | OmpSimdClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public R visit(OmpParallelForSimdClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <FOR>
    * f3 -> ( OmpParallelForClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public R visit(OmpParallelForConstruct n, A argu);

   /**
    * f0 -> OmpParallelForClause()
    * f1 -> ( ( "," )? OmpParallelForClause() )*
    */
   public R visit(OmpParallelForClauseList n, A argu);

   /**
    * f0 -> OmpParallelClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public R visit(OmpParallelForClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <SECTIONS>
    * f3 -> ( OmpParallelSectionsClauseList() )?
    * f4 -> OmpEol()
    * f5 -> SectionsScope()
    */
   public R visit(OmpParallelSectionsConstruct n, A argu);

   /**
    * f0 -> OmpParallelClause()
    *       | OmpLastPrivateClause()
    */
   public R visit(OmpParallelSectionsClauseList n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <MASTER>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public R visit(OmpMasterConstruct n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <CRITICAL>
    * f2 -> ( "(" OmpCriticalName() ")" ( <HINT> "(" Expression() ")" )? )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpCriticalConstruct n, A argu);

   /**
    * f0 -> "("
    * f1 -> <IDENTIFIER>
    * f2 -> ")"
    */
   public R visit(OmpCriticalName n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKGROUP>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public R visit(OmpTaskGroupConstruct n, A argu);

   /**
    * f0 -> OmpAtomicDefaultConstruct()
    *       | OmpAtomicClauseConstruct()
    */
   public R visit(OmpAtomicConstruct n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <ATOMIC>
    * f2 -> ( <SEQCST> ( "," )? )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpAtomicDefaultConstruct n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <ATOMIC>
    * f2 -> ( <SEQCST> ( "," )? )?
    * f3 -> AtomicClause()
    * f4 -> ( <SEQCST> ( "," )? )?
    * f5 -> OmpEol()
    * f6 -> Statement()
    */
   public R visit(OmpAtomicClauseConstruct n, A argu);

   /**
    * f0 -> <READ>
    *       | <WRITE>
    *       | <UPDATE>
    *       | <CAPTURE>
    */
   public R visit(AtomicClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <ORDERED>
    * f2 -> ( OmpOrderedClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public R visit(OmpOrderedConstruct n, A argu);

   /**
    * f0 -> OmpOrderedConstructClause()
    * f1 -> ( ( "," )? OmpOrderedConstructClause() )*
    */
   public R visit(OmpOrderedClauseList n, A argu);

   /**
    * f0 -> OmpThreadsClause()
    *       | OmpSimdOrderedClause()
    *       | OmpDependOrderedSourceClause()
    *       | OmpDependOrderedSinkClause()
    */
   public R visit(OmpOrderedConstructClause n, A argu);

   /**
    * f0 -> <THREADS>
    */
   public R visit(OmpThreadsClause n, A argu);

   /**
    * f0 -> <SIMD>
    */
   public R visit(OmpSimdOrderedClause n, A argu);

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> <SOURCE>
    * f3 -> ")"
    */
   public R visit(OmpDependOrderedSourceClause n, A argu);

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> <SINK>
    * f3 -> <COLON>
    * f4 -> OmpIterationVector()
    * f5 -> ")"
    */
   public R visit(OmpDependOrderedSinkClause n, A argu);

   /**
    * f0 -> OmpIterationDimension()
    * f1 -> ( "," OmpIterationDimension() )*
    */
   public R visit(OmpIterationVector n, A argu);

   /**
    * f0 -> OmpForwardDependence()
    *       | OmpBackwardDependence()
    */
   public R visit(OmpIterationDimension n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "+"
    * f2 -> ConstantExpression()
    */
   public R visit(OmpForwardDependence n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "-"
    * f2 -> ConstantExpression()
    */
   public R visit(OmpBackwardDependence n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKYIELD>
    * f2 -> OmpEol()
    */
   public R visit(OmpTaskyieldDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <ENTER>
    * f3 -> <DATA>
    * f4 -> ( OmpTargetEnterDataClauseList() )?
    */
   public R visit(OmpTargetEnterDataDirective n, A argu);

   /**
    * f0 -> OmpTargetEnterDataClause()
    * f1 -> ( ( "," )? OmpTargetEnterDataClause() )*
    */
   public R visit(OmpTargetEnterDataClauseList n, A argu);

   /**
    * f0 -> OmpIfTargetEnterDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpDependClause()
    *       | OmpNowaitClause()
    */
   public R visit(OmpTargetEnterDataClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <ENTER> <DATA> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfTargetEnterDataClause n, A argu);

   /**
    * f0 -> <DEVICE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpDeviceClause n, A argu);

   /**
    * f0 -> <MAP>
    * f1 -> "("
    * f2 -> ( ( OmpMapTypeModifier() ( "," )? )? OmpMapType() <COLON> )?
    * f3 -> VariableList()
    * f4 -> ")"
    */
   public R visit(OmpMapClause n, A argu);

   /**
    * f0 -> <ALWAYS>
    */
   public R visit(OmpMapTypeModifier n, A argu);

   /**
    * f0 -> <TO>
    *       | <FROM>
    *       | <TOFROM>
    *       | <ALLOC>
    *       | <RELEASE>
    *       | <DELETE>
    */
   public R visit(OmpMapType n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <EXIT>
    * f3 -> <DATA>
    * f4 -> ( OmpTargetExitDataClauseList() )?
    */
   public R visit(OmpTargetExitDataDirective n, A argu);

   /**
    * f0 -> OmpTargetExitDataClause()
    * f1 -> ( ( "," )? OmpTargetExitDataClause() )*
    */
   public R visit(OmpTargetExitDataClauseList n, A argu);

   /**
    * f0 -> OmpIfTargetExitDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpDependClause()
    *       | OmpNowaitClause()
    */
   public R visit(OmpTargetExitDataClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <EXIT> <DATA> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfTargetExitDataClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <UPDATE>
    * f3 -> OmpTargetUpdateClauseList()
    */
   public R visit(OmpTargetUpdateDirective n, A argu);

   /**
    * f0 -> OmpTargetUpdateClause()
    * f1 -> ( ( "," )? OmpTargetUpdateClause() )*
    */
   public R visit(OmpTargetUpdateClauseList n, A argu);

   /**
    * f0 -> OmpIfTargetUpdateClause()
    *       | OmpDeviceClause()
    *       | OmpNowaitClause()
    *       | OmpDependClause()
    *       | OmpToClause()
    *       | OmpFromClause()
    */
   public R visit(OmpTargetUpdateClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <UPDATE> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public R visit(OmpIfTargetUpdateClause n, A argu);

   /**
    * f0 -> <TO>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpToClause n, A argu);

   /**
    * f0 -> <FROM>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpFromClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <BARRIER>
    * f2 -> OmpEol()
    */
   public R visit(OmpBarrierDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKWAIT>
    * f2 -> OmpEol()
    */
   public R visit(OmpTaskwaitDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <FLUSH>
    * f2 -> ( "(" VariableList() ")" )?
    * f3 -> OmpEol()
    */
   public R visit(OmpFlushDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <CANCEL>
    * f2 -> OmpConstructTypeClause()
    * f3 -> ( ( "," )? OmpIfClause() )?
    * f4 -> OmpEol()
    */
   public R visit(OmpCancelDirective n, A argu);

   /**
    * f0 -> <PARALLEL>
    *       | <SECTIONS>
    *       | <FOR>
    *       | <TASKGROUP>
    */
   public R visit(OmpConstructTypeClause n, A argu);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public R visit(OmpIfClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <CANCELLATION>
    * f2 -> <POINT>
    * f3 -> OmpConstructTypeClause()
    * f4 -> OmpEol()
    */
   public R visit(OmpCancellationPointDirective n, A argu);

   /**
    * f0 -> OmpDeclareTargetExtendedListDirective()
    *       | OmpDeclareTargetListDirective()
    *       | OmpDeclareTargetDirective()
    *       | OmpDeclareSimdDirective()
    *       | OmpThreadPrivateDirective()
    *       | OmpDeclareReductionDirective()
    */
   public R visit(OmpGlobalDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> "("
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public R visit(OmpDeclareTargetExtendedListDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> OmpDeclareTargetClauseList()
    */
   public R visit(OmpDeclareTargetListDirective n, A argu);

   /**
    * f0 -> OmpDeclareTargetClause()
    * f1 -> ( ( "," )? OmpDeclareTargetClause() )*
    */
   public R visit(OmpDeclareTargetClauseList n, A argu);

   /**
    * f0 -> OmpToClause()
    *       | OmpLinkClause()
    */
   public R visit(OmpDeclareTargetClause n, A argu);

   /**
    * f0 -> <LINK>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpLinkClause n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> OmpEol()
    * f4 -> ( FunctionDefinitionOrDeclaration() )*
    * f5 -> OmpPragma()
    * f6 -> <END>
    * f7 -> <DECLARE>
    * f8 -> <TARGET>
    */
   public R visit(OmpDeclareTargetDirective n, A argu);

   /**
    * f0 -> OmpDeclareSimdPragmaList()
    * f1 -> FunctionDefinitionOrDeclaration()
    */
   public R visit(OmpDeclareSimdDirective n, A argu);

   /**
    * f0 -> OmpDeclareSimdPragma()
    * f1 -> ( OmpDeclareSimdPragma() )*
    */
   public R visit(OmpDeclareSimdPragmaList n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <SIMD>
    * f3 -> ( OmpDeclareSimdClauseList() )?
    */
   public R visit(OmpDeclareSimdPragma n, A argu);

   /**
    * f0 -> OmpDeclareSimdClause()
    * f1 -> ( ( "," )? OmpDeclareSimdClause() )*
    */
   public R visit(OmpDeclareSimdClauseList n, A argu);

   /**
    * f0 -> OmpSimdLenClause()
    *       | OmpLinearClause()
    *       | OmpAlignedClause()
    *       | OmpUniformClause()
    *       | OmpInbranchClause()
    *       | OmpNotinbranchClause()
    */
   public R visit(OmpDeclareSimdClause n, A argu);

   /**
    * f0 -> <UNIFORM>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public R visit(OmpUniformClause n, A argu);

   /**
    * f0 -> <INBRANCH>
    */
   public R visit(OmpInbranchClause n, A argu);

   /**
    * f0 -> <NOTINBRANCH>
    */
   public R visit(OmpNotinbranchClause n, A argu);

   /**
    * f0 -> Declaration()
    *       | FunctionDefinition()
    */
   public R visit(FunctionDefinitionOrDeclaration n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <THREADPRIVATE>
    * f2 -> "("
    * f3 -> VariableList()
    * f4 -> ")"
    * f5 -> OmpEol()
    */
   public R visit(OmpThreadPrivateDirective n, A argu);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <REDUCTION>
    * f3 -> "("
    * f4 -> ReductionOp()
    * f5 -> ":"
    * f6 -> ReductionTypeList()
    * f7 -> ":"
    * f8 -> Expression()
    * f9 -> ")"
    * f10 -> ( InitializerClause() )?
    * f11 -> OmpEol()
    */
   public R visit(OmpDeclareReductionDirective n, A argu);

   /**
    * f0 -> ( TypeSpecifier() )*
    */
   public R visit(ReductionTypeList n, A argu);

   /**
    * f0 -> AssignInitializerClause()
    *       | ArgumentInitializerClause()
    */
   public R visit(InitializerClause n, A argu);

   /**
    * f0 -> <INITIALIZER>
    * f1 -> "("
    * f2 -> <IDENTIFIER>
    * f3 -> "="
    * f4 -> Initializer()
    * f5 -> ")"
    */
   public R visit(AssignInitializerClause n, A argu);

   /**
    * f0 -> <INITIALIZER>
    * f1 -> "("
    * f2 -> <IDENTIFIER>
    * f3 -> "("
    * f4 -> ExpressionList()
    * f5 -> ")"
    * f6 -> ")"
    */
   public R visit(ArgumentInitializerClause n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    *       | "+"
    *       | "*"
    *       | "-"
    *       | "&"
    *       | "^"
    *       | "|"
    *       | "||"
    *       | "&&"
    */
   public R visit(ReductionOp n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public R visit(VariableList n, A argu);

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public R visit(Expression n, A argu);

   /**
    * f0 -> NonConditionalExpression()
    *       | ConditionalExpression()
    */
   public R visit(AssignmentExpression n, A argu);

   /**
    * f0 -> UnaryExpression()
    * f1 -> AssignmentOperator()
    * f2 -> AssignmentExpression()
    */
   public R visit(NonConditionalExpression n, A argu);

   /**
    * f0 -> "="
    *       | "*="
    *       | "/="
    *       | "%="
    *       | "+="
    *       | "-="
    *       | "<<="
    *       | ">>="
    *       | "&="
    *       | "^="
    *       | "|="
    */
   public R visit(AssignmentOperator n, A argu);

   /**
    * f0 -> LogicalORExpression()
    * f1 -> ( "?" Expression() ":" ConditionalExpression() )?
    */
   public R visit(ConditionalExpression n, A argu);

   /**
    * f0 -> ConditionalExpression()
    */
   public R visit(ConstantExpression n, A argu);

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> ( "||" LogicalORExpression() )?
    */
   public R visit(LogicalORExpression n, A argu);

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> ( "&&" LogicalANDExpression() )?
    */
   public R visit(LogicalANDExpression n, A argu);

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> ( "|" InclusiveORExpression() )?
    */
   public R visit(InclusiveORExpression n, A argu);

   /**
    * f0 -> ANDExpression()
    * f1 -> ( "^" ExclusiveORExpression() )?
    */
   public R visit(ExclusiveORExpression n, A argu);

   /**
    * f0 -> EqualityExpression()
    * f1 -> ( "&" ANDExpression() )?
    */
   public R visit(ANDExpression n, A argu);

   /**
    * f0 -> RelationalExpression()
    * f1 -> ( EqualOptionalExpression() )?
    */
   public R visit(EqualityExpression n, A argu);

   /**
    * f0 -> EqualExpression()
    *       | NonEqualExpression()
    */
   public R visit(EqualOptionalExpression n, A argu);

   /**
    * f0 -> "=="
    * f1 -> EqualityExpression()
    */
   public R visit(EqualExpression n, A argu);

   /**
    * f0 -> "!="
    * f1 -> EqualityExpression()
    */
   public R visit(NonEqualExpression n, A argu);

   /**
    * f0 -> ShiftExpression()
    * f1 -> ( RelationalOptionalExpression() )?
    */
   public R visit(RelationalExpression n, A argu);

   /**
    * f0 -> RelationalLTExpression()
    *       | RelationalGTExpression()
    *       | RelationalLEExpression()
    *       | RelationalGEExpression()
    */
   public R visit(RelationalOptionalExpression n, A argu);

   /**
    * f0 -> "<"
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalLTExpression n, A argu);

   /**
    * f0 -> ">"
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalGTExpression n, A argu);

   /**
    * f0 -> "<="
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalLEExpression n, A argu);

   /**
    * f0 -> ">="
    * f1 -> RelationalExpression()
    */
   public R visit(RelationalGEExpression n, A argu);

   /**
    * f0 -> AdditiveExpression()
    * f1 -> ( ShiftOptionalExpression() )?
    */
   public R visit(ShiftExpression n, A argu);

   /**
    * f0 -> ShiftLeftExpression()
    *       | ShiftRightExpression()
    */
   public R visit(ShiftOptionalExpression n, A argu);

   /**
    * f0 -> ">>"
    * f1 -> ShiftExpression()
    */
   public R visit(ShiftLeftExpression n, A argu);

   /**
    * f0 -> "<<"
    * f1 -> ShiftExpression()
    */
   public R visit(ShiftRightExpression n, A argu);

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> ( AdditiveOptionalExpression() )?
    */
   public R visit(AdditiveExpression n, A argu);

   /**
    * f0 -> AdditivePlusExpression()
    *       | AdditiveMinusExpression()
    */
   public R visit(AdditiveOptionalExpression n, A argu);

   /**
    * f0 -> "+"
    * f1 -> AdditiveExpression()
    */
   public R visit(AdditivePlusExpression n, A argu);

   /**
    * f0 -> "-"
    * f1 -> AdditiveExpression()
    */
   public R visit(AdditiveMinusExpression n, A argu);

   /**
    * f0 -> CastExpression()
    * f1 -> ( MultiplicativeOptionalExpression() )?
    */
   public R visit(MultiplicativeExpression n, A argu);

   /**
    * f0 -> MultiplicativeMultiExpression()
    *       | MultiplicativeDivExpression()
    *       | MultiplicativeModExpression()
    */
   public R visit(MultiplicativeOptionalExpression n, A argu);

   /**
    * f0 -> "*"
    * f1 -> MultiplicativeExpression()
    */
   public R visit(MultiplicativeMultiExpression n, A argu);

   /**
    * f0 -> "/"
    * f1 -> MultiplicativeExpression()
    */
   public R visit(MultiplicativeDivExpression n, A argu);

   /**
    * f0 -> "%"
    * f1 -> MultiplicativeExpression()
    */
   public R visit(MultiplicativeModExpression n, A argu);

   /**
    * f0 -> CastExpressionTyped()
    *       | UnaryExpression()
    */
   public R visit(CastExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> TypeName()
    * f2 -> ")"
    * f3 -> CastExpression()
    */
   public R visit(CastExpressionTyped n, A argu);

   /**
    * f0 -> UnaryExpressionPreIncrement()
    *       | UnaryExpressionPreDecrement()
    *       | UnarySizeofExpression()
    *       | UnaryCastExpression()
    *       | PostfixExpression()
    */
   public R visit(UnaryExpression n, A argu);

   /**
    * f0 -> "++"
    * f1 -> UnaryExpression()
    */
   public R visit(UnaryExpressionPreIncrement n, A argu);

   /**
    * f0 -> "--"
    * f1 -> UnaryExpression()
    */
   public R visit(UnaryExpressionPreDecrement n, A argu);

   /**
    * f0 -> UnaryOperator()
    * f1 -> CastExpression()
    */
   public R visit(UnaryCastExpression n, A argu);

   /**
    * f0 -> SizeofTypeName()
    *       | SizeofUnaryExpression()
    */
   public R visit(UnarySizeofExpression n, A argu);

   /**
    * f0 -> <SIZEOF>
    * f1 -> UnaryExpression()
    */
   public R visit(SizeofUnaryExpression n, A argu);

   /**
    * f0 -> <SIZEOF>
    * f1 -> "("
    * f2 -> TypeName()
    * f3 -> ")"
    */
   public R visit(SizeofTypeName n, A argu);

   /**
    * f0 -> "&"
    *       | "*"
    *       | "+"
    *       | "-"
    *       | "~"
    *       | "!"
    */
   public R visit(UnaryOperator n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> PostfixOperationsList()
    */
   public R visit(PostfixExpression n, A argu);

   /**
    * f0 -> ( APostfixOperation() )*
    */
   public R visit(PostfixOperationsList n, A argu);

   /**
    * f0 -> BracketExpression()
    *       | ArgumentList()
    *       | DotId()
    *       | ArrowId()
    *       | PlusPlus()
    *       | MinusMinus()
    */
   public R visit(APostfixOperation n, A argu);

   /**
    * f0 -> "++"
    */
   public R visit(PlusPlus n, A argu);

   /**
    * f0 -> "--"
    */
   public R visit(MinusMinus n, A argu);

   /**
    * f0 -> "["
    * f1 -> Expression()
    * f2 -> "]"
    */
   public R visit(BracketExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> ( ExpressionList() )?
    * f2 -> ")"
    */
   public R visit(ArgumentList n, A argu);

   /**
    * f0 -> "."
    * f1 -> <IDENTIFIER>
    */
   public R visit(DotId n, A argu);

   /**
    * f0 -> "->"
    * f1 -> <IDENTIFIER>
    */
   public R visit(ArrowId n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    *       | Constant()
    *       | ExpressionClosed()
    *       | GenericSelection()
    */
   public R visit(PrimaryExpression n, A argu);

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(ExpressionClosed n, A argu);

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public R visit(ExpressionList n, A argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | ( <STRING_LITERAL> )+
    */
   public R visit(Constant n, A argu);

   /**
    * f0 -> <_GENERIC>
    * f1 -> "("
    * f2 -> AssignmentExpression()
    * f3 -> ","
    * f4 -> GenericAssocList()
    * f5 -> ")"
    */
   public R visit(GenericSelection n, A argu);

   /**
    * f0 -> GenericAssociation()
    * f1 -> ( "," GenericAssociation() )*
    */
   public R visit(GenericAssocList n, A argu);

   /**
    * f0 -> TypeName() ":" AssignmentExpression()
    *       | <DFLT> ":" AssignmentExpression()
    */
   public R visit(GenericAssociation n, A argu);

}
