//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ElementsOfTranslation() )+
    */
   public void visit(TranslationUnit n);

   /**
    * f0 -> ExternalDeclaration()
    *       | UnknownCpp()
    *       | UnknownPragma()
    */
   public void visit(ElementsOfTranslation n);

   /**
    * f0 -> Declaration()
    *       | FunctionDefinition()
    *       | OmpGlobalDirective()
    */
   public void visit(ExternalDeclaration n);

   /**
    * f0 -> ( DeclarationSpecifiers() )?
    * f1 -> Declarator()
    * f2 -> ( DeclarationList() )?
    * f3 -> CompoundStatement()
    */
   public void visit(FunctionDefinition n);

   /**
    * f0 -> DeclarationSpecifiers() ( InitDeclaratorList() )? ";"
    *       | StaticAssertDeclaration()
    */
   public void visit(Declaration n);

   /**
    * f0 -> <STATIC_ASSERT>
    * f1 -> "("
    * f2 -> ConstantExpression()
    * f3 -> ","
    * f4 -> <STRING_LITERAL>
    * f5 -> ")"
    */
   public void visit(StaticAssertDeclaration n);

   /**
    * f0 -> ( Declaration() )+
    */
   public void visit(DeclarationList n);

   /**
    * f0 -> ( ADeclarationSpecifier() )+
    */
   public void visit(DeclarationSpecifiers n);

   /**
    * f0 -> StorageClassSpecifier()
    *       | TypeSpecifier()
    *       | TypeQualifier()
    *       | FunctionSpecifier()
    *       | AlignmentSpecifier()
    */
   public void visit(ADeclarationSpecifier n);

   /**
    * f0 -> <INLINE>
    *       | <NORETURN>
    */
   public void visit(FunctionSpecifier n);

   /**
    * f0 -> AlignAsTypeName()
    *       | AlignAsConstantExpression()
    */
   public void visit(AlignmentSpecifier n);

   /**
    * f0 -> <ALIGNAS>
    * f1 -> "("
    * f2 -> TypeName()
    * f3 -> ")"
    */
   public void visit(AlignAsTypeName n);

   /**
    * f0 -> <ALIGNAS>
    * f1 -> "("
    * f2 -> ConstantExpression()
    * f3 -> ")"
    */
   public void visit(AlignAsConstantExpression n);

   /**
    * f0 -> <AUTO>
    *       | <REGISTER>
    *       | <STATIC>
    *       | <EXTERN>
    *       | <TYPEDEF>
    */
   public void visit(StorageClassSpecifier n);

   /**
    * f0 -> ( <VOID> | <CHAR> | <SHORT> | <INT> | <LONG> | <FLOAT> | <DOUBLE> | <SIGNED> | <UNSIGNED> | StructOrUnionSpecifier() | EnumSpecifier() | TypedefName() )
    */
   public void visit(TypeSpecifier n);

   /**
    * f0 -> <RESTRICT>
    *       | <CONST>
    *       | <VOLATILE>
    *       | <CCONST>
    *       | <CSIGNED>
    *       | <CSIGNED2>
    */
   public void visit(TypeQualifier n);

   /**

    * f0 -> ( StructOrUnionSpecifierWithList() | StructOrUnionSpecifierWithId() )
    */
   public void visit(StructOrUnionSpecifier n);

   /**
    * f0 -> StructOrUnion()
    * f1 -> ( <IDENTIFIER> )?
    * f2 -> "{"
    * f3 -> StructDeclarationList()
    * f4 -> "}"
    */
   public void visit(StructOrUnionSpecifierWithList n);

   /**
    * f0 -> StructOrUnion()
    * f1 -> <IDENTIFIER>
    */
   public void visit(StructOrUnionSpecifierWithId n);

   /**
    * f0 -> <STRUCT>
    *       | <UNION>
    */
   public void visit(StructOrUnion n);

   /**
    * f0 -> ( StructDeclaration() )+
    */
   public void visit(StructDeclarationList n);

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( "," InitDeclarator() )*
    */
   public void visit(InitDeclaratorList n);

   /**
    * f0 -> Declarator()
    * f1 -> ( "=" Initializer() )?
    */
   public void visit(InitDeclarator n);

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> StructDeclaratorList()
    * f2 -> ";"
    */
   public void visit(StructDeclaration n);

   /**
    * f0 -> ( ASpecifierQualifier() )+
    */
   public void visit(SpecifierQualifierList n);

   /**
    * f0 -> TypeSpecifier()
    *       | TypeQualifier()
    */
   public void visit(ASpecifierQualifier n);

   /**
    * f0 -> StructDeclarator()
    * f1 -> ( "," StructDeclarator() )*
    */
   public void visit(StructDeclaratorList n);

   /**
    * f0 -> StructDeclaratorWithDeclarator()
    *       | StructDeclaratorWithBitField()
    */
   public void visit(StructDeclarator n);

   /**
    * f0 -> Declarator()
    * f1 -> ( ":" ConstantExpression() )?
    */
   public void visit(StructDeclaratorWithDeclarator n);

   /**
    * f0 -> ":"
    * f1 -> ConstantExpression()
    */
   public void visit(StructDeclaratorWithBitField n);

   /**
    * f0 -> EnumSpecifierWithList()
    *       | EnumSpecifierWithId()
    */
   public void visit(EnumSpecifier n);

   /**
    * f0 -> <ENUM>
    * f1 -> ( <IDENTIFIER> )?
    * f2 -> "{"
    * f3 -> EnumeratorList()
    * f4 -> "}"
    */
   public void visit(EnumSpecifierWithList n);

   /**
    * f0 -> <ENUM>
    * f1 -> <IDENTIFIER>
    */
   public void visit(EnumSpecifierWithId n);

   /**
    * f0 -> Enumerator()
    * f1 -> ( "," Enumerator() )*
    */
   public void visit(EnumeratorList n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "=" ConstantExpression() )?
    */
   public void visit(Enumerator n);

   /**
    * f0 -> ( Pointer() )?
    * f1 -> DirectDeclarator()
    */
   public void visit(Declarator n);

   /**
    * f0 -> IdentifierOrDeclarator()
    * f1 -> DeclaratorOpList()
    */
   public void visit(DirectDeclarator n);

   /**
    * f0 -> ( ADeclaratorOp() )*
    */
   public void visit(DeclaratorOpList n);

   /**
    * f0 -> DimensionSize()
    *       | ParameterTypeListClosed()
    *       | OldParameterListClosed()
    */
   public void visit(ADeclaratorOp n);

   /**
    * f0 -> "["
    * f1 -> ( ConstantExpression() )?
    * f2 -> "]"
    */
   public void visit(DimensionSize n);

   /**
    * f0 -> "("
    * f1 -> ( ParameterTypeList() )?
    * f2 -> ")"
    */
   public void visit(ParameterTypeListClosed n);

   /**
    * f0 -> "("
    * f1 -> ( OldParameterList() )?
    * f2 -> ")"
    */
   public void visit(OldParameterListClosed n);

   /**
    * f0 -> <IDENTIFIER>
    *       | "(" Declarator() ")"
    */
   public void visit(IdentifierOrDeclarator n);

   /**
    * f0 -> ( "*" | "^" )
    * f1 -> ( TypeQualifierList() )?
    * f2 -> ( Pointer() )?
    */
   public void visit(Pointer n);

   /**
    * f0 -> ( TypeQualifier() )+
    */
   public void visit(TypeQualifierList n);

   /**
    * f0 -> ParameterList()
    * f1 -> ( "," "..." )?
    */
   public void visit(ParameterTypeList n);

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( "," ParameterDeclaration() )*
    */
   public void visit(ParameterList n);

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ParameterAbstraction()
    */
   public void visit(ParameterDeclaration n);

   /**
    * f0 -> Declarator()
    *       | AbstractOptionalDeclarator()
    */
   public void visit(ParameterAbstraction n);

   /**
    * f0 -> ( AbstractDeclarator() )?
    */
   public void visit(AbstractOptionalDeclarator n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public void visit(OldParameterList n);

   /**
    * f0 -> AssignmentExpression()
    *       | ArrayInitializer()
    */
   public void visit(Initializer n);

   /**
    * f0 -> "{"
    * f1 -> InitializerList()
    * f2 -> ( "," )?
    * f3 -> "}"
    */
   public void visit(ArrayInitializer n);

   /**
    * f0 -> Initializer()
    * f1 -> ( "," Initializer() )*
    */
   public void visit(InitializerList n);

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> ( AbstractDeclarator() )?
    */
   public void visit(TypeName n);

   /**
    * f0 -> AbstractDeclaratorWithPointer()
    *       | DirectAbstractDeclarator()
    */
   public void visit(AbstractDeclarator n);

   /**
    * f0 -> Pointer()
    * f1 -> ( DirectAbstractDeclarator() )?
    */
   public void visit(AbstractDeclaratorWithPointer n);

   /**
    * f0 -> AbstractDimensionOrParameter()
    * f1 -> DimensionOrParameterList()
    */
   public void visit(DirectAbstractDeclarator n);

   /**
    * f0 -> AbstractDeclaratorClosed()
    *       | DimensionSize()
    *       | ParameterTypeListClosed()
    */
   public void visit(AbstractDimensionOrParameter n);

   /**
    * f0 -> "("
    * f1 -> AbstractDeclarator()
    * f2 -> ")"
    */
   public void visit(AbstractDeclaratorClosed n);

   /**
    * f0 -> ( ADimensionOrParameter() )*
    */
   public void visit(DimensionOrParameterList n);

   /**
    * f0 -> DimensionSize()
    *       | ParameterTypeListClosed()
    */
   public void visit(ADimensionOrParameter n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(TypedefName n);

   /**
    * f0 -> LabeledStatement()
    *       | ExpressionStatement()
    *       | CompoundStatement()
    *       | SelectionStatement()
    *       | IterationStatement()
    *       | JumpStatement()
    *       | UnknownPragma()
    *       | OmpConstruct()
    *       | OmpDirective()
    *       | UnknownCpp()
    */
   public void visit(Statement n);

   /**
    * f0 -> SimpleLabeledStatement()
    *       | CaseLabeledStatement()
    *       | DefaultLabeledStatement()
    */
   public void visit(LabeledStatement n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public void visit(SimpleLabeledStatement n);

   /**
    * f0 -> <CASE>
    * f1 -> ConstantExpression()
    * f2 -> ":"
    * f3 -> Statement()
    */
   public void visit(CaseLabeledStatement n);

   /**
    * f0 -> <DFLT>
    * f1 -> ":"
    * f2 -> Statement()
    */
   public void visit(DefaultLabeledStatement n);

   /**
    * f0 -> ( Expression() )?
    * f1 -> ";"
    */
   public void visit(ExpressionStatement n);

   /**
    * f0 -> "{"
    * f1 -> ( CompoundStatementElement() )*
    * f2 -> "}"
    */
   public void visit(CompoundStatement n);

   /**
    * f0 -> Declaration()
    *       | Statement()
    */
   public void visit(CompoundStatementElement n);

   /**
    * f0 -> IfStatement()
    *       | SwitchStatement()
    */
   public void visit(SelectionStatement n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> ( <ELSE> Statement() )?
    */
   public void visit(IfStatement n);

   /**
    * f0 -> <SWITCH>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(SwitchStatement n);

   /**
    * f0 -> WhileStatement()
    *       | DoStatement()
    *       | ForStatement()
    */
   public void visit(IterationStatement n);

   /**
    * f0 -> <WHILE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public void visit(WhileStatement n);

   /**
    * f0 -> <DO>
    * f1 -> Statement()
    * f2 -> <WHILE>
    * f3 -> "("
    * f4 -> Expression()
    * f5 -> ")"
    * f6 -> ";"
    */
   public void visit(DoStatement n);

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> ( Expression() )?
    * f3 -> ";"
    * f4 -> ( Expression() )?
    * f5 -> ";"
    * f6 -> ( Expression() )?
    * f7 -> ")"
    * f8 -> Statement()
    */
   public void visit(ForStatement n);

   /**
    * f0 -> GotoStatement()
    *       | ContinueStatement()
    *       | BreakStatement()
    *       | ReturnStatement()
    */
   public void visit(JumpStatement n);

   /**
    * f0 -> <GOTO>
    * f1 -> <IDENTIFIER>
    * f2 -> ";"
    */
   public void visit(GotoStatement n);

   /**
    * f0 -> <CONTINUE>
    * f1 -> ";"
    */
   public void visit(ContinueStatement n);

   /**
    * f0 -> <BREAK>
    * f1 -> ";"
    */
   public void visit(BreakStatement n);

   /**
    * f0 -> <RETURN>
    * f1 -> ( Expression() )?
    * f2 -> ";"
    */
   public void visit(ReturnStatement n);

   /**
    * f0 -> "#"
    * f1 -> <UNKNOWN_CPP>
    */
   public void visit(UnknownCpp n);

   /**
    * f0 -> <OMP_CR>
    *       | <OMP_NL>
    */
   public void visit(OmpEol n);

   /**
    * f0 -> OmpParallelConstruct()
    *       | OmpForConstruct()
    *       | OmpSectionsConstruct()
    *       | OmpSingleConstruct()
    *       | OmpSimdConstruct()
    *       | OmpForSimdConstruct()
    *       | OmpTaskConstruct()
    *       | OmpTaskLoopSimdConstruct()
    *       | OmpTaskLoopConstruct()
    *       | OmpTargetDataConstruct()
    *       | OmpTargetParallelForSimdConstruct()
    *       | OmpTargetParallelForConstruct()
    *       | OmpTargetParallelConstruct()
    *       | OmpTargetSimdConstruct()
    *       | OmpTargetTeamsDistributeParallelForSimdConstruct()
    *       | OmpTargetTeamsDistributeParallelForConstruct()
    *       | OmpTargetTeamsDistributeSimdConstruct()
    *       | OmpTargetTeamsDistributeConstruct()
    *       | OmpTargetTeamsConstruct()
    *       | OmpTargetConstruct()
    *       | OmpTeamsDistributeParallelForSimdConstruct()
    *       | OmpTeamsDistributeParallelForConstruct()
    *       | OmpTeamsDistributeSimdConstruct()
    *       | OmpTeamsDistributeConstruct()
    *       | OmpTeamsConstruct()
    *       | OmpDistributeSimdConstruct()
    *       | OmpDistributeParallelForSimdConstruct()
    *       | OmpDistributeParallelForConstruct()
    *       | OmpDistributeConstruct()
    *       | OmpParallelForSimdConstruct()
    *       | OmpParallelForConstruct()
    *       | OmpParallelSectionsConstruct()
    *       | OmpMasterConstruct()
    *       | OmpCriticalConstruct()
    *       | OmpTaskGroupConstruct()
    *       | OmpAtomicConstruct()
    *       | OmpOrderedConstruct()
    */
   public void visit(OmpConstruct n);

   /**
    * f0 -> OmpTaskyieldDirective()
    *       | OmpTargetEnterDataDirective()
    *       | OmpTargetExitDataDirective()
    *       | OmpTargetUpdateDirective()
    *       | OmpBarrierDirective()
    *       | OmpTaskwaitDirective()
    *       | OmpFlushDirective()
    *       | OmpCancelDirective()
    *       | OmpCancellationPointDirective()
    */
   public void visit(OmpDirective n);

   /**
    * f0 -> "#"
    * f1 -> <PRAGMA>
    * f2 -> <OMP>
    */
   public void visit(OmpPragma n);

   /**
    * f0 -> "#"
    * f1 -> <PRAGMA>
    * f2 -> <UNKNOWN_CPP>
    */
   public void visit(UnknownPragma n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> ( OmpParallelClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpParallelConstruct n);

   /**
    * f0 -> OmpParallelClause()
    * f1 -> ( ( "," )? OmpParallelClause() )*
    */
   public void visit(OmpParallelClauseList n);

   /**
    * f0 -> OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpCopyinClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    */
   public void visit(OmpParallelClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <PARALLEL> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfParallelClause n);

   /**
    * f0 -> <NUM_THREADS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpNumThreadsClause n);

   /**
    * f0 -> <DFLT>
    * f1 -> "("
    * f2 -> <SHARED>
    * f3 -> ")"
    */
   public void visit(OmpDfltSharedClause n);

   /**
    * f0 -> <DFLT>
    * f1 -> "("
    * f2 -> <NONE>
    * f3 -> ")"
    */
   public void visit(OmpDfltNoneClause n);

   /**
    * f0 -> <PRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpPrivateClause n);

   /**
    * f0 -> <FIRSTPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpFirstPrivateClause n);

   /**
    * f0 -> <SHARED>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpSharedClause n);

   /**
    * f0 -> <COPYIN>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpCopyinClause n);

   /**
    * f0 -> <REDUCTION>
    * f1 -> "("
    * f2 -> ReductionOp()
    * f3 -> ":"
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public void visit(OmpReductionClause n);

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <MASTER>
    * f3 -> ")"
    */
   public void visit(OmpThreadAffinityMasterClause n);

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <CLOSE>
    * f3 -> ")"
    */
   public void visit(OmpThreadAffinityCloseClause n);

   /**
    * f0 -> <PROC_BIND>
    * f1 -> "("
    * f2 -> <SPREAD>
    * f3 -> ")"
    */
   public void visit(OmpThreadAffinitySpreadClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <FOR>
    * f2 -> ( OmpForClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpForConstruct n);

   /**
    * f0 -> OmpForClause()
    * f1 -> ( ( "," )? OmpForClause() )*
    */
   public void visit(OmpForClauseList n);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpReductionClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpForClause n);

   /**
    * f0 -> <LASTPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpLastPrivateClause n);

   /**
    * f0 -> <LINEAR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ( <COLON> Expression() )?
    * f4 -> ")"
    */
   public void visit(OmpLinearClause n);

   /**
    * f0 -> <SCHEDULE>
    * f1 -> "("
    * f2 -> ( Modifier() ( "," Modifier() )? <COLON> )?
    * f3 -> ScheduleKind()
    * f4 -> ( "," Expression() )?
    * f5 -> ")"
    */
   public void visit(OmpScheduleClause n);

   /**
    * f0 -> <MONOTONIC>
    *       | <NONMONOTONIC>
    *       | <SIMD>
    */
   public void visit(Modifier n);

   /**
    * f0 -> <STATIC>
    *       | <DYNAMIC>
    *       | <GUIDED>
    *       | <RUNTIME>
    *       | <AUTO>
    */
   public void visit(ScheduleKind n);

   /**
    * f0 -> <COLLAPSE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpCollapseClause n);

   /**
    * f0 -> <ORDERED>
    * f1 -> ( "(" Expression() ")" )?
    */
   public void visit(OmpOrderedClause n);

   /**
    * f0 -> <NOWAIT>
    */
   public void visit(OmpNowaitClause n);

   /**
    * f0 -> <FOR>
    * f1 -> "("
    * f2 -> OmpForInitExpression()
    * f3 -> ";"
    * f4 -> OmpForCondition()
    * f5 -> ";"
    * f6 -> OmpForReinitExpression()
    * f7 -> ")"
    */
   public void visit(OmpForHeader n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> Expression()
    */
   public void visit(OmpForInitExpression n);

   /**
    * f0 -> OmpForLTCondition()
    *       | OmpForLECondition()
    *       | OmpForGTCondition()
    *       | OmpForGECondition()
    */
   public void visit(OmpForCondition n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "<"
    * f2 -> Expression()
    */
   public void visit(OmpForLTCondition n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "<="
    * f2 -> Expression()
    */
   public void visit(OmpForLECondition n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ">"
    * f2 -> Expression()
    */
   public void visit(OmpForGTCondition n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ">="
    * f2 -> Expression()
    */
   public void visit(OmpForGECondition n);

   /**
    * f0 -> PostIncrementId()
    *       | PostDecrementId()
    *       | PreIncrementId()
    *       | PreDecrementId()
    *       | ShortAssignPlus()
    *       | ShortAssignMinus()
    *       | OmpForAdditive()
    *       | OmpForSubtractive()
    *       | OmpForMultiplicative()
    */
   public void visit(OmpForReinitExpression n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "++"
    */
   public void visit(PostIncrementId n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "--"
    */
   public void visit(PostDecrementId n);

   /**
    * f0 -> "++"
    * f1 -> <IDENTIFIER>
    */
   public void visit(PreIncrementId n);

   /**
    * f0 -> "--"
    * f1 -> <IDENTIFIER>
    */
   public void visit(PreDecrementId n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "+="
    * f2 -> Expression()
    */
   public void visit(ShortAssignPlus n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "-="
    * f2 -> Expression()
    */
   public void visit(ShortAssignMinus n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> <IDENTIFIER>
    * f3 -> "+"
    * f4 -> AdditiveExpression()
    */
   public void visit(OmpForAdditive n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> <IDENTIFIER>
    * f3 -> "-"
    * f4 -> AdditiveExpression()
    */
   public void visit(OmpForSubtractive n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "="
    * f2 -> MultiplicativeExpression()
    * f3 -> "+"
    * f4 -> <IDENTIFIER>
    */
   public void visit(OmpForMultiplicative n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SECTIONS>
    * f2 -> ( OmpSectionsClauseList() )?
    * f3 -> OmpEol()
    * f4 -> SectionsScope()
    */
   public void visit(OmpSectionsConstruct n);

   /**
    * f0 -> OmpSectionsClause()
    * f1 -> ( ( "," )? OmpSectionsClause() )*
    */
   public void visit(OmpSectionsClauseList n);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpReductionClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpSectionsClause n);

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )?
    * f2 -> ( ASection() )*
    * f3 -> "}"
    */
   public void visit(SectionsScope n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SECTION>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public void visit(ASection n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SINGLE>
    * f2 -> ( OmpSingleClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpSingleConstruct n);

   /**
    * f0 -> OmpSingleClause()
    * f1 -> ( OmpSingleClause() )*
    */
   public void visit(OmpSingleClauseList n);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpCopyPrivateClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpSingleClause n);

   /**
    * f0 -> <COPYPRIVATE>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpCopyPrivateClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <SIMD>
    * f2 -> ( OmpSimdClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpSimdConstruct n);

   /**
    * f0 -> OmpSimdClause()
    * f1 -> ( ( "," )? OmpSimdClause() )*
    */
   public void visit(OmpSimdClauseList n);

   /**
    * f0 -> OmpSafeLenClause()
    *       | OmpSimdLenClause()
    *       | OmpLinearClause()
    *       | OmpAlignedClause()
    *       | OmpPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpReductionClause()
    *       | OmpCollapseClause()
    */
   public void visit(OmpSimdClause n);

   /**
    * f0 -> <SAFELEN>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpSafeLenClause n);

   /**
    * f0 -> <SIMDLEN>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpSimdLenClause n);

   /**
    * f0 -> <ALIGNED>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ( <COLON> Expression() )?
    * f4 -> ")"
    */
   public void visit(OmpAlignedClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <FOR>
    * f2 -> <SIMD>
    * f3 -> ( OmpForSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpForSimdConstruct n);

   /**
    * f0 -> OmpForSimdClause()
    * f1 -> ( ( "," )? OmpForSimdClause() )*
    */
   public void visit(OmpForSimdClauseList n);

   /**
    * f0 -> OmpSimdClause()
    *       | OmpForClause()
    */
   public void visit(OmpForSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASK>
    * f2 -> ( TaskClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpTaskConstruct n);

   /**
    * f0 -> TaskClause()
    * f1 -> ( ( "," )? TaskClause() )*
    */
   public void visit(TaskClauseList n);

   /**
    * f0 -> OmpIfTaskClause()
    *       | OmpFinalClause()
    *       | OmpUntiedClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpMergeableClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpDependClause()
    *       | OmpPriorityClause()
    */
   public void visit(TaskClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TASK> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTaskClause n);

   /**
    * f0 -> <FINAL>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpFinalClause n);

   /**
    * f0 -> <UNTIED>
    */
   public void visit(OmpUntiedClause n);

   /**
    * f0 -> <MERGEABLE>
    */
   public void visit(OmpMergeableClause n);

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> DependencyType()
    * f3 -> <COLON>
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public void visit(OmpDependClause n);

   /**
    * f0 -> <IN>
    *       | <OUT>
    *       | <INOUT>
    */
   public void visit(DependencyType n);

   /**
    * f0 -> <PRIORITY>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpPriorityClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKLOOP>
    * f2 -> <SIMD>
    * f3 -> ( OmpTaskLoopSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpTaskLoopSimdConstruct n);

   /**
    * f0 -> OmpTaskLoopSimdClause()
    * f1 -> ( ( "," )? OmpTaskLoopSimdClause() )*
    */
   public void visit(OmpTaskLoopSimdClauseList n);

   /**
    * f0 -> OmpSimdClause()
    *       | OmpTaskLoopClause()
    */
   public void visit(OmpTaskLoopSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKLOOP>
    * f2 -> ( OmpTaskLoopClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpTaskLoopConstruct n);

   /**
    * f0 -> OmpTaskLoopClause()
    * f1 -> ( ( "," )? OmpTaskLoopClause() )*
    */
   public void visit(OmpTaskLoopClauseList n);

   /**
    * f0 -> OmpIfTaskLoopClause()
    *       | OmpSharedClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpGrainSizeClause()
    *       | OmpNumTasksClause()
    *       | OmpCollapseClause()
    *       | OmpFinalClause()
    *       | OmpPriorityClause()
    *       | OmpUntiedClause()
    *       | OmpMergeableClause()
    *       | OmpNoGroupClause()
    */
   public void visit(OmpTaskLoopClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TASKLOOP> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTaskLoopClause n);

   /**
    * f0 -> <GRAINSIZE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpGrainSizeClause n);

   /**
    * f0 -> <NUMTASKS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpNumTasksClause n);

   /**
    * f0 -> <NOGROUP>
    */
   public void visit(OmpNoGroupClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <DATA>
    * f3 -> ( OmpTargetDataClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public void visit(OmpTargetDataConstruct n);

   /**
    * f0 -> OmpTargetDataClause()
    * f1 -> ( ( "," )? OmpTargetDataClause() )*
    */
   public void visit(OmpTargetDataClauseList n);

   /**
    * f0 -> OmpIfTargetDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpUseDevicePtrClause()
    */
   public void visit(OmpTargetDataClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> <TARGET>
    * f3 -> <DATA>
    * f4 -> Expression()
    * f5 -> ")"
    */
   public void visit(OmpIfTargetDataClause n);

   /**
    * f0 -> <USEDEVICEPTR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpUseDevicePtrClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> <SIMD>
    * f5 -> ( OmpTargetParallelForSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpTargetParallelForSimdConstruct n);

   /**
    * f0 -> OmpTargetParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTargetParallelForSimdClause() )*
    */
   public void visit(OmpTargetParallelForSimdClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpSimdClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpTargetParallelForSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> ( OmpTargetParallelForClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpTargetParallelForConstruct n);

   /**
    * f0 -> OmpTargetParallelForClause()
    * f1 -> ( ( "," )? OmpTargetParallelForClause() )*
    */
   public void visit(OmpTargetParallelForClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpTargetParallelForClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <PARALLEL>
    * f3 -> ( OmpTargetParallelClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public void visit(OmpTargetParallelConstruct n);

   /**
    * f0 -> OmpTargetParallelClause()
    * f1 -> ( ( "," )? OmpTargetParallelClause() )*
    */
   public void visit(OmpTargetParallelClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpIfParallelClause()
    *       | OmpNumThreadsClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    *       | OmpThreadAffinityMasterClause()
    *       | OmpThreadAffinityCloseClause()
    *       | OmpThreadAffinitySpreadClause()
    */
   public void visit(OmpTargetParallelClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <SIMD>
    * f3 -> ( OmpTargetSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpTargetSimdConstruct n);

   /**
    * f0 -> OmpTargetSimdClause()
    * f1 -> ( ( "," )? OmpTargetSimdClause() )*
    */
   public void visit(OmpTargetSimdClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpSimdClause()
    */
   public void visit(OmpTargetSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> <SIMD>
    * f6 -> ( OmpTargetTeamsDistributeParallelForSimdClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeParallelForSimdConstruct n);

   /**
    * f0 -> OmpTargetTeamsDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeParallelForSimdClause() )*
    */
   public void visit(OmpTargetTeamsDistributeParallelForSimdClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeParallelForSimdClause()
    */
   public void visit(OmpTargetTeamsDistributeParallelForSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> <PARALLEL>
    * f5 -> <FOR>
    * f6 -> ( OmpTargetTeamsDistributeParallelForClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeParallelForConstruct n);

   /**
    * f0 -> OmpTargetTeamsDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeParallelForClause() )*
    */
   public void visit(OmpTargetTeamsDistributeParallelForClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeParallelForClause()
    */
   public void visit(OmpTargetTeamsDistributeParallelForClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> <SIMD>
    * f5 -> ( OmpTargetTeamsDistributeSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeSimdConstruct n);

   /**
    * f0 -> OmpTargetTeamsDistributeSimdClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeSimdClause() )*
    */
   public void visit(OmpTargetTeamsDistributeSimdClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeSimdClause()
    */
   public void visit(OmpTargetTeamsDistributeSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> <DISTRIBUTE>
    * f4 -> ( OmpTargetTeamsDistributeClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpTargetTeamsDistributeConstruct n);

   /**
    * f0 -> OmpTargetTeamsDistributeClause()
    * f1 -> ( ( "," )? OmpTargetTeamsDistributeClause() )*
    */
   public void visit(OmpTargetTeamsDistributeClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsDistributeClause()
    */
   public void visit(OmpTargetTeamsDistributeClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <TEAMS>
    * f3 -> ( OmpTargetTeamsClauseList() )?
    * f4 -> OmpEol()
    * f5 -> Statement()
    */
   public void visit(OmpTargetTeamsConstruct n);

   /**
    * f0 -> OmpTargetTeamsClause()
    * f1 -> ( ( "," )? OmpTargetTeamsClause() )*
    */
   public void visit(OmpTargetTeamsClauseList n);

   /**
    * f0 -> OmpTargetClause()
    *       | OmpTeamsClause()
    */
   public void visit(OmpTargetTeamsClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> ( OmpTargetClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpTargetConstruct n);

   /**
    * f0 -> OmpTargetClause()
    * f1 -> ( ( "," )? OmpTargetClause() )*
    */
   public void visit(OmpTargetClauseList n);

   /**
    * f0 -> OmpIfTargetClause()
    *       | OmpDeviceClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpMapClause()
    *       | OmpIsDevicePtrListClause()
    *       | OmpDefaultMapClause()
    *       | OmpNowaitClause()
    *       | OmpDependClause()
    */
   public void visit(OmpTargetClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetClause n);

   /**
    * f0 -> <ISDEVICEPTR>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpIsDevicePtrListClause n);

   /**
    * f0 -> <DEFAULTMAP>
    * f1 -> "("
    * f2 -> <TOFROM>
    * f3 -> <COLON>
    * f4 -> <SCALAR>
    * f5 -> ")"
    */
   public void visit(OmpDefaultMapClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> <SIMD>
    * f6 -> ( OmpTeamsDistributeParallelForSimdClauseList() )?
    * f7 -> OmpEol()
    * f8 -> OmpForHeader()
    * f9 -> Statement()
    */
   public void visit(OmpTeamsDistributeParallelForSimdConstruct n);

   /**
    * f0 -> OmpTeamsDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeParallelForSimdClause() )*
    */
   public void visit(OmpTeamsDistributeParallelForSimdClauseList n);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeParallelForSimdClause()
    */
   public void visit(OmpTeamsDistributeParallelForSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <PARALLEL>
    * f4 -> <FOR>
    * f5 -> ( OmpTeamsDistributeParallelForClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpTeamsDistributeParallelForConstruct n);

   /**
    * f0 -> OmpTeamsDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeParallelForClause() )*
    */
   public void visit(OmpTeamsDistributeParallelForClauseList n);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeParallelForClause()
    */
   public void visit(OmpTeamsDistributeParallelForClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> <SIMD>
    * f4 -> ( OmpTeamsDistributeSimdClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpTeamsDistributeSimdConstruct n);

   /**
    * f0 -> OmpTeamsDistributeSimdClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeSimdClause() )*
    */
   public void visit(OmpTeamsDistributeSimdClauseList n);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeSimdClause()
    */
   public void visit(OmpTeamsDistributeSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> <DISTRIBUTE>
    * f3 -> ( OmpTeamsDistributeClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpTeamsDistributeConstruct n);

   /**
    * f0 -> OmpTeamsDistributeClause()
    * f1 -> ( ( "," )? OmpTeamsDistributeClause() )*
    */
   public void visit(OmpTeamsDistributeClauseList n);

   /**
    * f0 -> OmpTeamsClause()
    *       | OmpDistributeClause()
    */
   public void visit(OmpTeamsDistributeClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TEAMS>
    * f2 -> ( OmpTeamsClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpTeamsConstruct n);

   /**
    * f0 -> OmpTeamsClause()
    * f1 -> ( ( "," )? OmpTeamsClause() )*
    */
   public void visit(OmpTeamsClauseList n);

   /**
    * f0 -> OmpNumTeamsClause()
    *       | OmpThreadLimitClause()
    *       | OmpDfltSharedClause()
    *       | OmpDfltNoneClause()
    *       | OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpSharedClause()
    *       | OmpReductionClause()
    */
   public void visit(OmpTeamsClause n);

   /**
    * f0 -> <NUMTEAMS>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpNumTeamsClause n);

   /**
    * f0 -> <THREADLIMIT>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpThreadLimitClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <SIMD>
    * f3 -> ( OmpDistributeSimdClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpDistributeSimdConstruct n);

   /**
    * f0 -> OmpDistributeSimdClause()
    * f1 -> ( ( "," )? OmpDistributeSimdClause() )*
    */
   public void visit(OmpDistributeSimdClauseList n);

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpSimdClause()
    */
   public void visit(OmpDistributeSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> <SIMD>
    * f5 -> ( OmpDistributeParallelForSimdClauseList() )?
    * f6 -> OmpEol()
    * f7 -> OmpForHeader()
    * f8 -> Statement()
    */
   public void visit(OmpDistributeParallelForSimdConstruct n);

   /**
    * f0 -> OmpDistributeParallelForSimdClause()
    * f1 -> ( ( "," )? OmpDistributeParallelForSimdClause() )*
    */
   public void visit(OmpDistributeParallelForSimdClauseList n);

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpParallelForSimdClause()
    */
   public void visit(OmpDistributeParallelForSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> <PARALLEL>
    * f3 -> <FOR>
    * f4 -> ( OmpDistributeParallelForClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpDistributeParallelForConstruct n);

   /**
    * f0 -> OmpDistributeParallelForClause()
    * f1 -> ( ( "," )? OmpDistributeParallelForClause() )*
    */
   public void visit(OmpDistributeParallelForClauseList n);

   /**
    * f0 -> OmpDistributeClause()
    *       | OmpParallelForClause()
    */
   public void visit(OmpDistributeParallelForClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DISTRIBUTE>
    * f2 -> ( OmpDistributeClauseList() )?
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public void visit(OmpDistributeConstruct n);

   /**
    * f0 -> OmpDistributeClause()
    * f1 -> ( ( "," )? OmpDistributeClause() )*
    */
   public void visit(OmpDistributeClauseList n);

   /**
    * f0 -> OmpPrivateClause()
    *       | OmpFirstPrivateClause()
    *       | OmpLastPrivateClause()
    *       | OmpCollapseClause()
    *       | OmpDistScheduleClause()
    */
   public void visit(OmpDistributeClause n);

   /**
    * f0 -> <DISTSCHEDULE>
    * f1 -> "("
    * f2 -> ScheduleKind()
    * f3 -> ( "," Expression() )?
    * f4 -> ")"
    */
   public void visit(OmpDistScheduleClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <FOR>
    * f3 -> <SIMD>
    * f4 -> ( OmpParallelForSimdClauseList() )?
    * f5 -> OmpEol()
    * f6 -> OmpForHeader()
    * f7 -> Statement()
    */
   public void visit(OmpParallelForSimdConstruct n);

   /**
    * f0 -> OmpParallelForSimdClause()
    * f1 -> ( ( "," )? OmpParallelForSimdClause() )*
    */
   public void visit(OmpParallelForSimdClauseList n);

   /**
    * f0 -> OmpParallelClause()
    *       | OmpSimdClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpParallelForSimdClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <FOR>
    * f3 -> ( OmpParallelForClauseList() )?
    * f4 -> OmpEol()
    * f5 -> OmpForHeader()
    * f6 -> Statement()
    */
   public void visit(OmpParallelForConstruct n);

   /**
    * f0 -> OmpParallelForClause()
    * f1 -> ( ( "," )? OmpParallelForClause() )*
    */
   public void visit(OmpParallelForClauseList n);

   /**
    * f0 -> OmpParallelClause()
    *       | OmpLastPrivateClause()
    *       | OmpLinearClause()
    *       | OmpScheduleClause()
    *       | OmpCollapseClause()
    *       | OmpOrderedClause()
    */
   public void visit(OmpParallelForClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <PARALLEL>
    * f2 -> <SECTIONS>
    * f3 -> ( OmpParallelSectionsClauseList() )?
    * f4 -> OmpEol()
    * f5 -> SectionsScope()
    */
   public void visit(OmpParallelSectionsConstruct n);

   /**
    * f0 -> OmpParallelClause()
    *       | OmpLastPrivateClause()
    */
   public void visit(OmpParallelSectionsClauseList n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <MASTER>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public void visit(OmpMasterConstruct n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <CRITICAL>
    * f2 -> ( "(" OmpCriticalName() ")" ( <HINT> "(" Expression() ")" )? )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpCriticalConstruct n);

   /**
    * f0 -> "("
    * f1 -> <IDENTIFIER>
    * f2 -> ")"
    */
   public void visit(OmpCriticalName n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKGROUP>
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public void visit(OmpTaskGroupConstruct n);

   /**
    * f0 -> OmpAtomicDefaultConstruct()
    *       | OmpAtomicClauseConstruct()
    */
   public void visit(OmpAtomicConstruct n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <ATOMIC>
    * f2 -> ( <SEQCST> ( "," )? )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpAtomicDefaultConstruct n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <ATOMIC>
    * f2 -> ( <SEQCST> ( "," )? )?
    * f3 -> AtomicClause()
    * f4 -> ( <SEQCST> ( "," )? )?
    * f5 -> OmpEol()
    * f6 -> Statement()
    */
   public void visit(OmpAtomicClauseConstruct n);

   /**
    * f0 -> <READ>
    *       | <WRITE>
    *       | <UPDATE>
    *       | <CAPTURE>
    */
   public void visit(AtomicClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <ORDERED>
    * f2 -> ( OmpOrderedClauseList() )?
    * f3 -> OmpEol()
    * f4 -> Statement()
    */
   public void visit(OmpOrderedConstruct n);

   /**
    * f0 -> OmpOrderedConstructClause()
    * f1 -> ( ( "," )? OmpOrderedConstructClause() )*
    */
   public void visit(OmpOrderedClauseList n);

   /**
    * f0 -> OmpThreadsClause()
    *       | OmpSimdOrderedClause()
    *       | OmpDependOrderedSourceClause()
    *       | OmpDependOrderedSinkClause()
    */
   public void visit(OmpOrderedConstructClause n);

   /**
    * f0 -> <THREADS>
    */
   public void visit(OmpThreadsClause n);

   /**
    * f0 -> <SIMD>
    */
   public void visit(OmpSimdOrderedClause n);

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> <SOURCE>
    * f3 -> ")"
    */
   public void visit(OmpDependOrderedSourceClause n);

   /**
    * f0 -> <DEPEND>
    * f1 -> "("
    * f2 -> <SINK>
    * f3 -> <COLON>
    * f4 -> OmpIterationVector()
    * f5 -> ")"
    */
   public void visit(OmpDependOrderedSinkClause n);

   /**
    * f0 -> OmpIterationDimension()
    * f1 -> ( "," OmpIterationDimension() )*
    */
   public void visit(OmpIterationVector n);

   /**
    * f0 -> OmpForwardDependence()
    *       | OmpBackwardDependence()
    */
   public void visit(OmpIterationDimension n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "+"
    * f2 -> ConstantExpression()
    */
   public void visit(OmpForwardDependence n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> "-"
    * f2 -> ConstantExpression()
    */
   public void visit(OmpBackwardDependence n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKYIELD>
    * f2 -> OmpEol()
    */
   public void visit(OmpTaskyieldDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <ENTER>
    * f3 -> <DATA>
    * f4 -> ( OmpTargetEnterDataClauseList() )?
    */
   public void visit(OmpTargetEnterDataDirective n);

   /**
    * f0 -> OmpTargetEnterDataClause()
    * f1 -> ( ( "," )? OmpTargetEnterDataClause() )*
    */
   public void visit(OmpTargetEnterDataClauseList n);

   /**
    * f0 -> OmpIfTargetEnterDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpDependClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpTargetEnterDataClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <ENTER> <DATA> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetEnterDataClause n);

   /**
    * f0 -> <DEVICE>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpDeviceClause n);

   /**
    * f0 -> <MAP>
    * f1 -> "("
    * f2 -> ( ( OmpMapTypeModifier() ( "," )? )? OmpMapType() <COLON> )?
    * f3 -> VariableList()
    * f4 -> ")"
    */
   public void visit(OmpMapClause n);

   /**
    * f0 -> <ALWAYS>
    */
   public void visit(OmpMapTypeModifier n);

   /**
    * f0 -> <TO>
    *       | <FROM>
    *       | <TOFROM>
    *       | <ALLOC>
    *       | <RELEASE>
    *       | <DELETE>
    */
   public void visit(OmpMapType n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <EXIT>
    * f3 -> <DATA>
    * f4 -> ( OmpTargetExitDataClauseList() )?
    */
   public void visit(OmpTargetExitDataDirective n);

   /**
    * f0 -> OmpTargetExitDataClause()
    * f1 -> ( ( "," )? OmpTargetExitDataClause() )*
    */
   public void visit(OmpTargetExitDataClauseList n);

   /**
    * f0 -> OmpIfTargetExitDataClause()
    *       | OmpDeviceClause()
    *       | OmpMapClause()
    *       | OmpDependClause()
    *       | OmpNowaitClause()
    */
   public void visit(OmpTargetExitDataClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <EXIT> <DATA> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetExitDataClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TARGET>
    * f2 -> <UPDATE>
    * f3 -> OmpTargetUpdateClauseList()
    */
   public void visit(OmpTargetUpdateDirective n);

   /**
    * f0 -> OmpTargetUpdateClause()
    * f1 -> ( ( "," )? OmpTargetUpdateClause() )*
    */
   public void visit(OmpTargetUpdateClauseList n);

   /**
    * f0 -> OmpIfTargetUpdateClause()
    *       | OmpDeviceClause()
    *       | OmpNowaitClause()
    *       | OmpDependClause()
    *       | OmpToClause()
    *       | OmpFromClause()
    */
   public void visit(OmpTargetUpdateClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> ( <TARGET> <UPDATE> <COLON> )?
    * f3 -> Expression()
    * f4 -> ")"
    */
   public void visit(OmpIfTargetUpdateClause n);

   /**
    * f0 -> <TO>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpToClause n);

   /**
    * f0 -> <FROM>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpFromClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <BARRIER>
    * f2 -> OmpEol()
    */
   public void visit(OmpBarrierDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <TASKWAIT>
    * f2 -> OmpEol()
    */
   public void visit(OmpTaskwaitDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <FLUSH>
    * f2 -> ( "(" VariableList() ")" )?
    * f3 -> OmpEol()
    */
   public void visit(OmpFlushDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <CANCEL>
    * f2 -> OmpConstructTypeClause()
    * f3 -> ( ( "," )? OmpIfClause() )?
    * f4 -> OmpEol()
    */
   public void visit(OmpCancelDirective n);

   /**
    * f0 -> <PARALLEL>
    *       | <SECTIONS>
    *       | <FOR>
    *       | <TASKGROUP>
    */
   public void visit(OmpConstructTypeClause n);

   /**
    * f0 -> <IF>
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    */
   public void visit(OmpIfClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <CANCELLATION>
    * f2 -> <POINT>
    * f3 -> OmpConstructTypeClause()
    * f4 -> OmpEol()
    */
   public void visit(OmpCancellationPointDirective n);

   /**
    * f0 -> OmpDeclareTargetExtendedListDirective()
    *       | OmpDeclareTargetListDirective()
    *       | OmpDeclareTargetDirective()
    *       | OmpDeclareSimdDirective()
    *       | OmpThreadPrivateDirective()
    *       | OmpDeclareReductionDirective()
    */
   public void visit(OmpGlobalDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> "("
    * f4 -> VariableList()
    * f5 -> ")"
    */
   public void visit(OmpDeclareTargetExtendedListDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> OmpDeclareTargetClauseList()
    */
   public void visit(OmpDeclareTargetListDirective n);

   /**
    * f0 -> OmpDeclareTargetClause()
    * f1 -> ( ( "," )? OmpDeclareTargetClause() )*
    */
   public void visit(OmpDeclareTargetClauseList n);

   /**
    * f0 -> OmpToClause()
    *       | OmpLinkClause()
    */
   public void visit(OmpDeclareTargetClause n);

   /**
    * f0 -> <LINK>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpLinkClause n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <TARGET>
    * f3 -> OmpEol()
    * f4 -> ( FunctionDefinitionOrDeclaration() )*
    * f5 -> OmpPragma()
    * f6 -> <END>
    * f7 -> <DECLARE>
    * f8 -> <TARGET>
    */
   public void visit(OmpDeclareTargetDirective n);

   /**
    * f0 -> OmpDeclareSimdPragmaList()
    * f1 -> FunctionDefinitionOrDeclaration()
    */
   public void visit(OmpDeclareSimdDirective n);

   /**
    * f0 -> OmpDeclareSimdPragma()
    * f1 -> ( OmpDeclareSimdPragma() )*
    */
   public void visit(OmpDeclareSimdPragmaList n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <SIMD>
    * f3 -> ( OmpDeclareSimdClauseList() )?
    */
   public void visit(OmpDeclareSimdPragma n);

   /**
    * f0 -> OmpDeclareSimdClause()
    * f1 -> ( ( "," )? OmpDeclareSimdClause() )*
    */
   public void visit(OmpDeclareSimdClauseList n);

   /**
    * f0 -> OmpSimdLenClause()
    *       | OmpLinearClause()
    *       | OmpAlignedClause()
    *       | OmpUniformClause()
    *       | OmpInbranchClause()
    *       | OmpNotinbranchClause()
    */
   public void visit(OmpDeclareSimdClause n);

   /**
    * f0 -> <UNIFORM>
    * f1 -> "("
    * f2 -> VariableList()
    * f3 -> ")"
    */
   public void visit(OmpUniformClause n);

   /**
    * f0 -> <INBRANCH>
    */
   public void visit(OmpInbranchClause n);

   /**
    * f0 -> <NOTINBRANCH>
    */
   public void visit(OmpNotinbranchClause n);

   /**
    * f0 -> Declaration()
    *       | FunctionDefinition()
    */
   public void visit(FunctionDefinitionOrDeclaration n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <THREADPRIVATE>
    * f2 -> "("
    * f3 -> VariableList()
    * f4 -> ")"
    * f5 -> OmpEol()
    */
   public void visit(OmpThreadPrivateDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <DECLARE>
    * f2 -> <REDUCTION>
    * f3 -> "("
    * f4 -> ReductionOp()
    * f5 -> ":"
    * f6 -> ReductionTypeList()
    * f7 -> ":"
    * f8 -> Expression()
    * f9 -> ")"
    * f10 -> ( InitializerClause() )?
    * f11 -> OmpEol()
    */
   public void visit(OmpDeclareReductionDirective n);

   /**
    * f0 -> ( TypeSpecifier() )*
    */
   public void visit(ReductionTypeList n);

   /**
    * f0 -> AssignInitializerClause()
    *       | ArgumentInitializerClause()
    */
   public void visit(InitializerClause n);

   /**
    * f0 -> <INITIALIZER>
    * f1 -> "("
    * f2 -> <IDENTIFIER>
    * f3 -> "="
    * f4 -> Initializer()
    * f5 -> ")"
    */
   public void visit(AssignInitializerClause n);

   /**
    * f0 -> <INITIALIZER>
    * f1 -> "("
    * f2 -> <IDENTIFIER>
    * f3 -> "("
    * f4 -> ExpressionList()
    * f5 -> ")"
    * f6 -> ")"
    */
   public void visit(ArgumentInitializerClause n);

   /**
    * f0 -> <IDENTIFIER>
    *       | "+"
    *       | "*"
    *       | "-"
    *       | "&"
    *       | "^"
    *       | "|"
    *       | "||"
    *       | "&&"
    */
   public void visit(ReductionOp n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( "," <IDENTIFIER> )*
    */
   public void visit(VariableList n);

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public void visit(Expression n);

   /**
    * f0 -> NonConditionalExpression()
    *       | ConditionalExpression()
    */
   public void visit(AssignmentExpression n);

   /**
    * f0 -> UnaryExpression()
    * f1 -> AssignmentOperator()
    * f2 -> AssignmentExpression()
    */
   public void visit(NonConditionalExpression n);

   /**
    * f0 -> "="
    *       | "*="
    *       | "/="
    *       | "%="
    *       | "+="
    *       | "-="
    *       | "<<="
    *       | ">>="
    *       | "&="
    *       | "^="
    *       | "|="
    */
   public void visit(AssignmentOperator n);

   /**
    * f0 -> LogicalORExpression()
    * f1 -> ( "?" Expression() ":" ConditionalExpression() )?
    */
   public void visit(ConditionalExpression n);

   /**
    * f0 -> ConditionalExpression()
    */
   public void visit(ConstantExpression n);

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> ( "||" LogicalORExpression() )?
    */
   public void visit(LogicalORExpression n);

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> ( "&&" LogicalANDExpression() )?
    */
   public void visit(LogicalANDExpression n);

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> ( "|" InclusiveORExpression() )?
    */
   public void visit(InclusiveORExpression n);

   /**
    * f0 -> ANDExpression()
    * f1 -> ( "^" ExclusiveORExpression() )?
    */
   public void visit(ExclusiveORExpression n);

   /**
    * f0 -> EqualityExpression()
    * f1 -> ( "&" ANDExpression() )?
    */
   public void visit(ANDExpression n);

   /**
    * f0 -> RelationalExpression()
    * f1 -> ( EqualOptionalExpression() )?
    */
   public void visit(EqualityExpression n);

   /**
    * f0 -> EqualExpression()
    *       | NonEqualExpression()
    */
   public void visit(EqualOptionalExpression n);

   /**
    * f0 -> "=="
    * f1 -> EqualityExpression()
    */
   public void visit(EqualExpression n);

   /**
    * f0 -> "!="
    * f1 -> EqualityExpression()
    */
   public void visit(NonEqualExpression n);

   /**
    * f0 -> ShiftExpression()
    * f1 -> ( RelationalOptionalExpression() )?
    */
   public void visit(RelationalExpression n);

   /**
    * f0 -> RelationalLTExpression()
    *       | RelationalGTExpression()
    *       | RelationalLEExpression()
    *       | RelationalGEExpression()
    */
   public void visit(RelationalOptionalExpression n);

   /**
    * f0 -> "<"
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalLTExpression n);

   /**
    * f0 -> ">"
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalGTExpression n);

   /**
    * f0 -> "<="
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalLEExpression n);

   /**
    * f0 -> ">="
    * f1 -> RelationalExpression()
    */
   public void visit(RelationalGEExpression n);

   /**
    * f0 -> AdditiveExpression()
    * f1 -> ( ShiftOptionalExpression() )?
    */
   public void visit(ShiftExpression n);

   /**
    * f0 -> ShiftLeftExpression()
    *       | ShiftRightExpression()
    */
   public void visit(ShiftOptionalExpression n);

   /**
    * f0 -> ">>"
    * f1 -> ShiftExpression()
    */
   public void visit(ShiftLeftExpression n);

   /**
    * f0 -> "<<"
    * f1 -> ShiftExpression()
    */
   public void visit(ShiftRightExpression n);

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> ( AdditiveOptionalExpression() )?
    */
   public void visit(AdditiveExpression n);

   /**
    * f0 -> AdditivePlusExpression()
    *       | AdditiveMinusExpression()
    */
   public void visit(AdditiveOptionalExpression n);

   /**
    * f0 -> "+"
    * f1 -> AdditiveExpression()
    */
   public void visit(AdditivePlusExpression n);

   /**
    * f0 -> "-"
    * f1 -> AdditiveExpression()
    */
   public void visit(AdditiveMinusExpression n);

   /**
    * f0 -> CastExpression()
    * f1 -> ( MultiplicativeOptionalExpression() )?
    */
   public void visit(MultiplicativeExpression n);

   /**
    * f0 -> MultiplicativeMultiExpression()
    *       | MultiplicativeDivExpression()
    *       | MultiplicativeModExpression()
    */
   public void visit(MultiplicativeOptionalExpression n);

   /**
    * f0 -> "*"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeMultiExpression n);

   /**
    * f0 -> "/"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeDivExpression n);

   /**
    * f0 -> "%"
    * f1 -> MultiplicativeExpression()
    */
   public void visit(MultiplicativeModExpression n);

   /**
    * f0 -> CastExpressionTyped()
    *       | UnaryExpression()
    */
   public void visit(CastExpression n);

   /**
    * f0 -> "("
    * f1 -> TypeName()
    * f2 -> ")"
    * f3 -> CastExpression()
    */
   public void visit(CastExpressionTyped n);

   /**
    * f0 -> UnaryExpressionPreIncrement()
    *       | UnaryExpressionPreDecrement()
    *       | UnarySizeofExpression()
    *       | UnaryCastExpression()
    *       | PostfixExpression()
    */
   public void visit(UnaryExpression n);

   /**
    * f0 -> "++"
    * f1 -> UnaryExpression()
    */
   public void visit(UnaryExpressionPreIncrement n);

   /**
    * f0 -> "--"
    * f1 -> UnaryExpression()
    */
   public void visit(UnaryExpressionPreDecrement n);

   /**
    * f0 -> UnaryOperator()
    * f1 -> CastExpression()
    */
   public void visit(UnaryCastExpression n);

   /**
    * f0 -> SizeofTypeName()
    *       | SizeofUnaryExpression()
    */
   public void visit(UnarySizeofExpression n);

   /**
    * f0 -> <SIZEOF>
    * f1 -> UnaryExpression()
    */
   public void visit(SizeofUnaryExpression n);

   /**
    * f0 -> <SIZEOF>
    * f1 -> "("
    * f2 -> TypeName()
    * f3 -> ")"
    */
   public void visit(SizeofTypeName n);

   /**
    * f0 -> "&"
    *       | "*"
    *       | "+"
    *       | "-"
    *       | "~"
    *       | "!"
    */
   public void visit(UnaryOperator n);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> PostfixOperationsList()
    */
   public void visit(PostfixExpression n);

   /**
    * f0 -> ( APostfixOperation() )*
    */
   public void visit(PostfixOperationsList n);

   /**
    * f0 -> BracketExpression()
    *       | ArgumentList()
    *       | DotId()
    *       | ArrowId()
    *       | PlusPlus()
    *       | MinusMinus()
    */
   public void visit(APostfixOperation n);

   /**
    * f0 -> "++"
    */
   public void visit(PlusPlus n);

   /**
    * f0 -> "--"
    */
   public void visit(MinusMinus n);

   /**
    * f0 -> "["
    * f1 -> Expression()
    * f2 -> "]"
    */
   public void visit(BracketExpression n);

   /**
    * f0 -> "("
    * f1 -> ( ExpressionList() )?
    * f2 -> ")"
    */
   public void visit(ArgumentList n);

   /**
    * f0 -> "."
    * f1 -> <IDENTIFIER>
    */
   public void visit(DotId n);

   /**
    * f0 -> "->"
    * f1 -> <IDENTIFIER>
    */
   public void visit(ArrowId n);

   /**
    * f0 -> <IDENTIFIER>
    *       | Constant()
    *       | ExpressionClosed()
    *       | GenericSelection()
    */
   public void visit(PrimaryExpression n);

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public void visit(ExpressionClosed n);

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( "," AssignmentExpression() )*
    */
   public void visit(ExpressionList n);

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | ( <STRING_LITERAL> )+
    */
   public void visit(Constant n);

   /**
    * f0 -> <_GENERIC>
    * f1 -> "("
    * f2 -> AssignmentExpression()
    * f3 -> ","
    * f4 -> GenericAssocList()
    * f5 -> ")"
    */
   public void visit(GenericSelection n);

   /**
    * f0 -> GenericAssociation()
    * f1 -> ( "," GenericAssociation() )*
    */
   public void visit(GenericAssocList n);

   /**
    * f0 -> TypeName() ":" AssignmentExpression()
    *       | <DFLT> ":" AssignmentExpression()
    */
   public void visit(GenericAssociation n);

}

