//#include<algorithm.h>
//#include<array>
//#include<bitset.h>
//#include<chrono.h>
#include<complex.h>
//#include<condition_variable.h>
//#include<deque.h>
//#include<exception.h>
//#include<forward_list.h>
//#include<fstream.h>
//#include<functional.h>
//#include<future.h>
//#include<initalizer_list.h>
//#include<iomanip.h>
#include<ios.h>
#include<iosfwd.h>
#include<iostream.h>
#include<istream.h>
#include<iterator.h>
#include<limits.h>
#include<list.h>
#include<locale.h>
#include<map.h>
#include<memory.h>
#include<mutex.h>
#include<new.h>
#include<numeric.h>
#include<ostream.h>
#include<queue.h>
#include<random.h>
#include<ratio.h>
#include<regex.h>
#include<set.h>
#include<sstream.h>
#include<stack.h>
#include<stdexcept.h>
#include<streambuf.h>
#include<string.h>
#include<system_error.h>
#include<thread.h>
#include<tuple.h>
#include<type_traits.h>
#include<typeinfo.h>
#include<unordered_map.h>
#include<unordered_set.h>
#include<utility.h>
#include<valarray.h>
#include<vector.h> 	 
