//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <PRIVATE> <LEFTPAREN> VariableList() <RIGHTPAREN>
 *       | <FIRSTPRIVATE> <LEFTPAREN> VariableList() <RIGHTPAREN>
 *       | <LASTPRIVATE> <LEFTPAREN> VariableList() <RIGHTPAREN>
 *       | <SHARED> <LEFTPAREN> VariableList() <RIGHTPAREN>
 *       | <COPYIN> <LEFTPAREN> VariableList() <RIGHTPAREN>
 *       | <DFLT> <LEFTPAREN> ( <SHARED> | <NONE> ) <RIGHTPAREN>
 *       | <REDUCTION> <LEFTPAREN> ReductionOp() <COLON> VariableList() <RIGHTPAREN>
 */
public class DataClause implements Node {
   public NodeChoice f0;

   public DataClause(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

