//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ForDirective()
 * f1 -> OmpForHeader()
 * f2 -> Statement()
 */
public class ForConstruct implements Node {
   public ForDirective f0;
   public OmpForHeader f1;
   public Statement f2;

   public ForConstruct(ForDirective n0, OmpForHeader n1, Statement n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

