//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <FOR>
 * f1 -> ( UniqueForClause() | DataClause() | <NOWAIT> )*
 * f2 -> OmpEol()
 */
public class ForDirective implements Node {
   public NodeToken f0;
   public NodeListOptional f1;
   public OmpEol f2;

   public ForDirective(NodeToken n0, NodeListOptional n1, OmpEol n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public ForDirective(NodeListOptional n0, OmpEol n1) {
      f0 = new NodeToken("for");
      f1 = n0;
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

