//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <PARALLEL>
 * f1 -> <SECTIONS>
 * f2 -> ( UniqueParallelClause() | DataClause() )*
 * f3 -> OmpEol()
 * f4 -> SectionsScope()
 */
public class ParallelSectionsConstruct implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeListOptional f2;
   public OmpEol f3;
   public SectionsScope f4;

   public ParallelSectionsConstruct(NodeToken n0, NodeToken n1, NodeListOptional n2, OmpEol n3, SectionsScope n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public ParallelSectionsConstruct(NodeListOptional n0, OmpEol n1, SectionsScope n2) {
      f0 = new NodeToken("parallel");
      f1 = new NodeToken("sections");
      f2 = n0;
      f3 = n1;
      f4 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

