//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <PARALLEL>
 * f1 -> <FOR>
 * f2 -> ( UniqueParallelClause() | UniqueForClause() | DataClause() )*
 * f3 -> OmpEol()
 * f4 -> OmpForHeader()
 * f5 -> Statement()
 */
public class ParallelForConstruct implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeListOptional f2;
   public OmpEol f3;
   public OmpForHeader f4;
   public Statement f5;

   public ParallelForConstruct(NodeToken n0, NodeToken n1, NodeListOptional n2, OmpEol n3, OmpForHeader n4, Statement n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public ParallelForConstruct(NodeListOptional n0, OmpEol n1, OmpForHeader n2, Statement n3) {
      f0 = new NodeToken("parallel");
      f1 = new NodeToken("for");
      f2 = n0;
      f3 = n1;
      f4 = n2;
      f5 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

