//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <SECTIONS>
 * f1 -> ( <NOWAIT> | DataClause() )*
 * f2 -> OmpEol()
 * f3 -> SectionsScope()
 */
public class SectionsConstruct implements Node {
   public NodeToken f0;
   public NodeListOptional f1;
   public OmpEol f2;
   public SectionsScope f3;

   public SectionsConstruct(NodeToken n0, NodeListOptional n1, OmpEol n2, SectionsScope n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public SectionsConstruct(NodeListOptional n0, OmpEol n1, SectionsScope n2) {
      f0 = new NodeToken("sections");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

