//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <THREADPRIVATE>
 * f2 -> <LEFTPAREN>
 * f3 -> VariableList()
 * f4 -> <RIGHTPAREN>
 * f5 -> OmpEol()
 */
public class ThreadprivateDirective implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeToken f2;
   public VariableList f3;
   public NodeToken f4;
   public OmpEol f5;

   public ThreadprivateDirective(OmpPragma n0, NodeToken n1, NodeToken n2, VariableList n3, NodeToken n4, OmpEol n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public ThreadprivateDirective(OmpPragma n0, VariableList n1, OmpEol n2) {
      f0 = n0;
      f1 = new NodeToken("threadprivate");
      f2 = new NodeToken("(");
      f3 = n1;
      f4 = new NodeToken(")");
      f5 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

