//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ExternalDeclaration() | UnknownCpp() | UnknownPragma() )+
    */
   public R visit(TranslationUnit n);

   /**
    * f0 -> ( FunctionDefinition() | Declaration() | ThreadprivateDirective() )
    */
   public R visit(ExternalDeclaration n);

   /**
    * f0 -> [ DeclarationSpecifiers() ]
    * f1 -> Declarator()
    * f2 -> [ DeclarationList() ]
    * f3 -> CompoundStatement()
    */
   public R visit(FunctionDefinition n);

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> [ InitDeclaratorList() ]
    * f2 -> <SEMICOLON>
    */
   public R visit(Declaration n);

   /**
    * f0 -> ( Declaration() )+
    */
   public R visit(DeclarationList n);

   /**
    * f0 -> ( StorageClassSpecifier() | TypeSpecifier() | TypeQualifier() )+
    */
   public R visit(DeclarationSpecifiers n);

   /**
    * f0 -> <AUTO>
    *       | <REGISTER>
    *       | <STATIC>
    *       | <EXTERN>
    *       | <TYPEDEF>
    */
   public R visit(StorageClassSpecifier n);

   /**
    * f0 -> <VOID>
    *       | <CHAR>
    *       | <SHORT>
    *       | <INT>
    *       | <LONG>
    *       | <FLOAT>
    *       | <DOUBLE>
    *       | <SIGNED>
    *       | <UNSIGNED>
    *       | StructOrUnionSpecifier()
    *       | EnumSpecifier()
    *       | TypedefName()
    */
   public R visit(TypeSpecifier n);

   /**
    * f0 -> <RESTRICT>
    *       | <CONST>
    *       | <VOLATILE>
    *       | <CCONST>
    */
   public R visit(TypeQualifier n);

   /**

    * f0 -> StructOrUnion()
    * f1 -> ( [ <IDENTIFIER> ] <LEFTBRACE> StructDeclarationList() <RIGHTBRACE> | <IDENTIFIER> )
    */
   public R visit(StructOrUnionSpecifier n);

   /**
    * f0 -> <STRUCT>
    *       | <UNION>
    */
   public R visit(StructOrUnion n);

   /**
    * f0 -> ( StructDeclaration() )+
    */
   public R visit(StructDeclarationList n);

   /**
    * f0 -> InitDeclarator()
    * f1 -> ( <COMMA> InitDeclarator() )*
    */
   public R visit(InitDeclaratorList n);

   /**
    * f0 -> Declarator()
    * f1 -> [ <OP_ASS> Initializer() ]
    */
   public R visit(InitDeclarator n);

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> StructDeclaratorList()
    * f2 -> <SEMICOLON>
    */
   public R visit(StructDeclaration n);

   /**
    * f0 -> ( TypeSpecifier() | TypeQualifier() )+
    */
   public R visit(SpecifierQualifierList n);

   /**
    * f0 -> StructDeclarator()
    * f1 -> ( <COMMA> StructDeclarator() )*
    */
   public R visit(StructDeclaratorList n);

   /**
    * f0 -> Declarator() [ <COLON> ConstantExpression() ]
    *       | <COLON> ConstantExpression()
    */
   public R visit(StructDeclarator n);

   /**
    * f0 -> <ENUM>
    * f1 -> ( [ <IDENTIFIER> ] <LEFTBRACE> EnumeratorList() <RIGHTBRACE> | <IDENTIFIER> )
    */
   public R visit(EnumSpecifier n);

   /**
    * f0 -> Enumerator()
    * f1 -> ( <COMMA> Enumerator() )*
    */
   public R visit(EnumeratorList n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> [ <OP_ASS> ConstantExpression() ]
    */
   public R visit(Enumerator n);

   /**
    * f0 -> [ Pointer() ]
    * f1 -> DirectDeclarator()
    */
   public R visit(Declarator n);

   /**
    * f0 -> ( <IDENTIFIER> | <LEFTPAREN> Declarator() <RIGHTPAREN> )
    * f1 -> ( <LEFTBRACKET> [ ConstantExpression() ] <RIGHTBRACKET> | <LEFTPAREN> ParameterTypeList() <RIGHTPAREN> | <LEFTPAREN> [ IdentifierList() ] <RIGHTPAREN> )*
    */
   public R visit(DirectDeclarator n);

   /**
    * f0 -> <OP_MUL>
    * f1 -> [ TypeQualifierList() ]
    * f2 -> [ Pointer() ]
    */
   public R visit(Pointer n);

   /**
    * f0 -> ( TypeQualifier() )+
    */
   public R visit(TypeQualifierList n);

   /**
    * f0 -> ParameterList()
    * f1 -> [ <COMMA> <ELLIPSIS> ]
    */
   public R visit(ParameterTypeList n);

   /**
    * f0 -> ParameterDeclaration()
    * f1 -> ( <COMMA> ParameterDeclaration() )*
    */
   public R visit(ParameterList n);

   /**
    * f0 -> DeclarationSpecifiers()
    * f1 -> ( Declarator() | [ AbstractDeclarator() ] )
    */
   public R visit(ParameterDeclaration n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( <COMMA> <IDENTIFIER> )*
    */
   public R visit(IdentifierList n);

   /**
    * f0 -> AssignmentExpression()
    *       | <LEFTBRACE> InitializerList() [ <COMMA> ] <RIGHTBRACE>
    */
   public R visit(Initializer n);

   /**
    * f0 -> Initializer()
    * f1 -> ( <COMMA> Initializer() )*
    */
   public R visit(InitializerList n);

   /**
    * f0 -> SpecifierQualifierList()
    * f1 -> [ AbstractDeclarator() ]
    */
   public R visit(TypeName n);

   /**
    * f0 -> ( Pointer() [ DirectAbstractDeclarator() ] | DirectAbstractDeclarator() )
    */
   public R visit(AbstractDeclarator n);

   /**
    * f0 -> ( <LEFTPAREN> AbstractDeclarator() <RIGHTPAREN> | <LEFTBRACKET> [ ConstantExpression() ] <RIGHTBRACKET> | <LEFTPAREN> [ ParameterTypeList() ] <RIGHTPAREN> )
    * f1 -> ( <LEFTBRACKET> [ ConstantExpression() ] <RIGHTBRACKET> | <LEFTPAREN> [ ParameterTypeList() ] <RIGHTPAREN> )*
    */
   public R visit(DirectAbstractDeclarator n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(TypedefName n);

   /**
    * f0 -> ( LabeledStatement() | ExpressionStatement() | CompoundStatement() | SelectionStatement() | IterationStatement() | JumpStatement() | UnknownPragma() | OmpConstruct() | OmpDirective() | UnknownCpp() )
    */
   public R visit(Statement n);

   /**
    * f0 -> <CROSSBAR>
    * f1 -> <UNKNOWN_CPP>
    */
   public R visit(UnknownCpp n);

   /**
    * f0 -> <OMP_CR>
    *       | <OMP_NL>
    */
   public R visit(OmpEol n);

   /**
    * f0 -> OmpPragma()
    * f1 -> ( ParallelConstruct() | ParallelForConstruct() | ParallelSectionsConstruct() | ForConstruct() | SectionsConstruct() | SingleConstruct() | MasterConstruct() | CriticalConstruct() | AtomicConstruct() | OrderedConstruct() )
    */
   public R visit(OmpConstruct n);

   /**
    * f0 -> OmpPragma()
    * f1 -> ( BarrierDirective() | FlushDirective() )
    */
   public R visit(OmpDirective n);

   /**
    * f0 -> ParallelDirective()
    * f1 -> Statement()
    */
   public R visit(ParallelConstruct n);

   /**
    * f0 -> <CROSSBAR>
    * f1 -> <PRAGMA>
    * f2 -> <OMP>
    */
   public R visit(OmpPragma n);

   /**
    * f0 -> <CROSSBAR>
    * f1 -> <PRAGMA>
    * f2 -> <UNKNOWN_CPP>
    */
   public R visit(UnknownPragma n);

   /**
    * f0 -> <PARALLEL>
    * f1 -> ( UniqueParallelClause() | DataClause() )*
    * f2 -> OmpEol()
    */
   public R visit(ParallelDirective n);

   /**
    * f0 -> <IF>
    * f1 -> <LEFTPAREN>
    * f2 -> Expression()
    * f3 -> <RIGHTPAREN>
    */
   public R visit(UniqueParallelClause n);

   /**
    * f0 -> ForDirective()
    * f1 -> OmpForHeader()
    * f2 -> Statement()
    */
   public R visit(ForConstruct n);

   /**
    * f0 -> <FOR>
    * f1 -> ( UniqueForClause() | DataClause() | <NOWAIT> )*
    * f2 -> OmpEol()
    */
   public R visit(ForDirective n);

   /**
    * f0 -> <ORDERED>
    *       | <SCHEDULE> <LEFTPAREN> ScheduleKind() [ <COMMA> Expression() ] <RIGHTPAREN>
    */
   public R visit(UniqueForClause n);

   /**
    * f0 -> <STATIC>
    *       | <DYNAMIC>
    *       | <GUIDED>
    *       | <RUNTIME>
    */
   public R visit(ScheduleKind n);

   /**
    * f0 -> <FOR>
    * f1 -> <LEFTPAREN>
    * f2 -> OmpForInitExpression()
    * f3 -> <SEMICOLON>
    * f4 -> OmpForCondition()
    * f5 -> <SEMICOLON>
    * f6 -> OmpForReinitExpression()
    * f7 -> <RIGHTPAREN>
    */
   public R visit(OmpForHeader n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> <OP_ASS>
    * f2 -> Expression()
    */
   public R visit(OmpForInitExpression n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( <OP_LT> | <OP_LE> | <OP_GT> | <OP_GE> )
    * f2 -> Expression()
    */
   public R visit(OmpForCondition n);

   /**
    * f0 -> ( <OP_INCR> | <OP_DECR> ) <IDENTIFIER>
    *       | <IDENTIFIER> ( <OP_INCR> | <OP_DECR> )
    *       | <IDENTIFIER> ( <OP_ADDASS> | <OP_SUBASS> ) Expression()
    *       | <IDENTIFIER> <OP_ASS> ( <IDENTIFIER> ( <OP_ADD> | <OP_SUB> ) AdditiveExpression() | MultiplicativeExpression() <OP_ADD> <IDENTIFIER> )
    */
   public R visit(OmpForReinitExpression n);

   /**
    * f0 -> <SECTIONS>
    * f1 -> ( <NOWAIT> | DataClause() )*
    * f2 -> OmpEol()
    * f3 -> SectionsScope()
    */
   public R visit(SectionsConstruct n);

   /**
    * f0 -> <LEFTBRACE>
    * f1 -> [ Statement() ]
    * f2 -> ( OmpPragma() <SECTION> OmpEol() Statement() )*
    * f3 -> <RIGHTBRACE>
    */
   public R visit(SectionsScope n);

   /**
    * f0 -> <SINGLE>
    * f1 -> ( <NOWAIT> | DataClause() )*
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public R visit(SingleConstruct n);

   /**
    * f0 -> <PARALLEL>
    * f1 -> <FOR>
    * f2 -> ( UniqueParallelClause() | UniqueForClause() | DataClause() )*
    * f3 -> OmpEol()
    * f4 -> OmpForHeader()
    * f5 -> Statement()
    */
   public R visit(ParallelForConstruct n);

   /**
    * f0 -> <PARALLEL>
    * f1 -> <SECTIONS>
    * f2 -> ( UniqueParallelClause() | DataClause() )*
    * f3 -> OmpEol()
    * f4 -> SectionsScope()
    */
   public R visit(ParallelSectionsConstruct n);

   /**
    * f0 -> <MASTER>
    * f1 -> OmpEol()
    * f2 -> Statement()
    */
   public R visit(MasterConstruct n);

   /**
    * f0 -> <CRITICAL>
    * f1 -> [ <LEFTPAREN> <IDENTIFIER> <RIGHTPAREN> ]
    * f2 -> OmpEol()
    * f3 -> Statement()
    */
   public R visit(CriticalConstruct n);

   /**
    * f0 -> <ATOMIC>
    * f1 -> OmpEol()
    * f2 -> ExpressionStatement()
    */
   public R visit(AtomicConstruct n);

   /**
    * f0 -> <FLUSH>
    * f1 -> [ <LEFTPAREN> VariableList() <RIGHTPAREN> ]
    * f2 -> OmpEol()
    */
   public R visit(FlushDirective n);

   /**
    * f0 -> <ORDERED>
    * f1 -> OmpEol()
    * f2 -> Statement()
    */
   public R visit(OrderedConstruct n);

   /**
    * f0 -> <BARRIER>
    * f1 -> OmpEol()
    */
   public R visit(BarrierDirective n);

   /**
    * f0 -> OmpPragma()
    * f1 -> <THREADPRIVATE>
    * f2 -> <LEFTPAREN>
    * f3 -> VariableList()
    * f4 -> <RIGHTPAREN>
    * f5 -> OmpEol()
    */
   public R visit(ThreadprivateDirective n);

   /**
    * f0 -> <PRIVATE> <LEFTPAREN> VariableList() <RIGHTPAREN>
    *       | <FIRSTPRIVATE> <LEFTPAREN> VariableList() <RIGHTPAREN>
    *       | <LASTPRIVATE> <LEFTPAREN> VariableList() <RIGHTPAREN>
    *       | <SHARED> <LEFTPAREN> VariableList() <RIGHTPAREN>
    *       | <COPYIN> <LEFTPAREN> VariableList() <RIGHTPAREN>
    *       | <DFLT> <LEFTPAREN> ( <SHARED> | <NONE> ) <RIGHTPAREN>
    *       | <REDUCTION> <LEFTPAREN> ReductionOp() <COLON> VariableList() <RIGHTPAREN>
    */
   public R visit(DataClause n);

   /**
    * f0 -> <OP_ADD>
    *       | <OP_MUL>
    *       | <OP_SUB>
    *       | <OP_BITAND>
    *       | <OP_BITXOR>
    *       | <OP_BITOR>
    *       | <OP_OR>
    *       | <OP_AND>
    */
   public R visit(ReductionOp n);

   /**
    * f0 -> <IDENTIFIER>
    * f1 -> ( <COMMA> <IDENTIFIER> )*
    */
   public R visit(VariableList n);

   /**
    * f0 -> ( <IDENTIFIER> <COLON> Statement() | <CASE> ConstantExpression() <COLON> Statement() | <DFLT> <COLON> Statement() )
    */
   public R visit(LabeledStatement n);

   /**
    * f0 -> [ Expression() ]
    * f1 -> <SEMICOLON>
    */
   public R visit(ExpressionStatement n);

   /**
    * f0 -> <LEFTBRACE>
    * f1 -> [ DeclarationList() ]
    * f2 -> [ StatementList() ]
    * f3 -> <RIGHTBRACE>
    */
   public R visit(CompoundStatement n);

   /**
    * f0 -> ( Statement() )+
    */
   public R visit(StatementList n);

   /**
    * f0 -> ( <IF> <LEFTPAREN> Expression() <RIGHTPAREN> Statement() [ <ELSE> Statement() ] | <SWITCH> <LEFTPAREN> Expression() <RIGHTPAREN> Statement() )
    */
   public R visit(SelectionStatement n);

   /**
    * f0 -> ( <WHILE> <LEFTPAREN> Expression() <RIGHTPAREN> Statement() | <DO> Statement() <WHILE> <LEFTPAREN> Expression() <RIGHTPAREN> <SEMICOLON> | <FOR> <LEFTPAREN> [ Expression() ] <SEMICOLON> [ Expression() ] <SEMICOLON> [ Expression() ] <RIGHTPAREN> Statement() )
    */
   public R visit(IterationStatement n);

   /**
    * f0 -> ( <GOTO> <IDENTIFIER> <SEMICOLON> | <CONTINUE> <SEMICOLON> | <BREAK> <SEMICOLON> | <RETURN> [ Expression() ] <SEMICOLON> )
    */
   public R visit(JumpStatement n);

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( <COMMA> AssignmentExpression() )*
    */
   public R visit(Expression n);

   /**
    * f0 -> UnaryExpression() AssignmentOperator() AssignmentExpression()
    *       | ConditionalExpression()
    */
   public R visit(AssignmentExpression n);

   /**
    * f0 -> ( <OP_ASS> | <OP_MULASS> | <OP_DIVASS> | <OP_MODASS> | <OP_ADDASS> | <OP_SUBASS> | <OP_SLASS> | <OP_SRASS> | <OP_ANDASS> | <OP_XORASS> | <OP_ORASS> )
    */
   public R visit(AssignmentOperator n);

   /**
    * f0 -> LogicalORExpression()
    * f1 -> [ <QUESTION> Expression() <COLON> ConditionalExpression() ]
    */
   public R visit(ConditionalExpression n);

   /**
    * f0 -> ConditionalExpression()
    */
   public R visit(ConstantExpression n);

   /**
    * f0 -> LogicalANDExpression()
    * f1 -> [ <OP_OR> LogicalORExpression() ]
    */
   public R visit(LogicalORExpression n);

   /**
    * f0 -> InclusiveORExpression()
    * f1 -> [ <OP_AND> LogicalANDExpression() ]
    */
   public R visit(LogicalANDExpression n);

   /**
    * f0 -> ExclusiveORExpression()
    * f1 -> [ <OP_BITOR> InclusiveORExpression() ]
    */
   public R visit(InclusiveORExpression n);

   /**
    * f0 -> ANDExpression()
    * f1 -> [ <OP_BITXOR> ExclusiveORExpression() ]
    */
   public R visit(ExclusiveORExpression n);

   /**
    * f0 -> EqualityExpression()
    * f1 -> [ <OP_BITAND> ANDExpression() ]
    */
   public R visit(ANDExpression n);

   /**
    * f0 -> RelationalExpression()
    * f1 -> [ ( <OP_EQ> | <OP_NEQ> ) EqualityExpression() ]
    */
   public R visit(EqualityExpression n);

   /**
    * f0 -> ShiftExpression()
    * f1 -> [ ( <OP_LT> | <OP_GT> | <OP_LE> | <OP_GE> ) RelationalExpression() ]
    */
   public R visit(RelationalExpression n);

   /**
    * f0 -> AdditiveExpression()
    * f1 -> [ ( <OP_SL> | <OP_SR> ) ShiftExpression() ]
    */
   public R visit(ShiftExpression n);

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> [ ( <OP_ADD> | <OP_SUB> ) AdditiveExpression() ]
    */
   public R visit(AdditiveExpression n);

   /**
    * f0 -> CastExpression()
    * f1 -> [ ( <OP_MUL> | <OP_DIV> | <OP_MOD> ) MultiplicativeExpression() ]
    */
   public R visit(MultiplicativeExpression n);

   /**
    * f0 -> ( <LEFTPAREN> TypeName() <RIGHTPAREN> CastExpression() | UnaryExpression() )
    */
   public R visit(CastExpression n);

   /**
    * f0 -> ( PostfixExpression() | <OP_INCR> UnaryExpression() | <OP_DECR> UnaryExpression() | UnaryOperator() CastExpression() | <SIZEOF> ( UnaryExpression() | <LEFTPAREN> TypeName() <RIGHTPAREN> ) )
    */
   public R visit(UnaryExpression n);

   /**
    * f0 -> ( <OP_BITAND> | <OP_MUL> | <OP_ADD> | <OP_SUB> | <OP_BITNOT> | <OP_NOT> )
    */
   public R visit(UnaryOperator n);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ( <LEFTBRACKET> Expression() <RIGHTBRACKET> | <LEFTPAREN> [ ArgumentExpressionList() ] <RIGHTPAREN> | <DOT> <IDENTIFIER> | <OP_DEREF> <IDENTIFIER> | <OP_INCR> | <OP_DECR> )*
    */
   public R visit(PostfixExpression n);

   /**
    * f0 -> ( <IDENTIFIER> | Constant() | <LEFTPAREN> Expression() <RIGHTPAREN> )
    */
   public R visit(PrimaryExpression n);

   /**
    * f0 -> AssignmentExpression()
    * f1 -> ( <COMMA> AssignmentExpression() )*
    */
   public R visit(ArgumentExpressionList n);

   /**
    * f0 -> <INTEGER_LITERAL>
    *       | <FLOATING_POINT_LITERAL>
    *       | <CHARACTER_LITERAL>
    *       | ( <STRING_LITERAL> )+
    */
   public R visit(Constant n);

}

