//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <ENUM>
 * f1 -> ( <IDENTIFIER> )?
 * f2 -> "{"
 * f3 -> EnumeratorList()
 * f4 -> "}"
 */
public class EnumSpecifierWithList implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeToken f2;
   public EnumeratorList f3;
   public NodeToken f4;

   public EnumSpecifierWithList(NodeToken n0, NodeOptional n1, NodeToken n2, EnumeratorList n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public EnumSpecifierWithList(NodeOptional n0, EnumeratorList n1) {
      f0 = new NodeToken("enum");
      f1 = n0;
      f2 = new NodeToken("{");
      f3 = n1;
      f4 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

