//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <FLUSH>
 * f2 -> ( FlushVars() )?
 * f3 -> OmpEol()
 */
public class FlushDirective implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeOptional f2;
   public OmpEol f3;

   public FlushDirective(OmpPragma n0, NodeToken n1, NodeOptional n2, OmpEol n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public FlushDirective(OmpPragma n0, NodeOptional n1, OmpEol n2) {
      f0 = n0;
      f1 = new NodeToken("flush");
      f2 = n1;
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

