//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> ForDirective()
 * f2 -> OmpForHeader()
 * f3 -> Statement()
 */
public class ForConstruct implements Node {
   public OmpPragma f0;
   public ForDirective f1;
   public OmpForHeader f2;
   public Statement f3;

   public ForConstruct(OmpPragma n0, ForDirective n1, OmpForHeader n2, Statement n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

