//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <ATOMIC>
 * f2 -> ( <SEQCST> ( "," )? )?
 * f3 -> AtomicClause()
 * f4 -> ( <SEQCST> ( "," )? )?
 * f5 -> OmpEol()
 * f6 -> Statement()
 */
public class OmpAtomicClauseConstruct implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeOptional f2;
   public AtomicClause f3;
   public NodeOptional f4;
   public OmpEol f5;
   public Statement f6;

   public OmpAtomicClauseConstruct(OmpPragma n0, NodeToken n1, NodeOptional n2, AtomicClause n3, NodeOptional n4, OmpEol n5, Statement n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public OmpAtomicClauseConstruct(OmpPragma n0, NodeOptional n1, AtomicClause n2, NodeOptional n3, OmpEol n4, Statement n5) {
      f0 = n0;
      f1 = new NodeToken("atomic");
      f2 = n1;
      f3 = n2;
      f4 = n3;
      f5 = n4;
      f6 = n5;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

