//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <CANCELLATION>
 * f2 -> <POINT>
 * f3 -> OmpConstructTypeClause()
 * f4 -> OmpEol()
 */
public class OmpCancellationPointDirective implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeToken f2;
   public OmpConstructTypeClause f3;
   public OmpEol f4;

   public OmpCancellationPointDirective(OmpPragma n0, NodeToken n1, NodeToken n2, OmpConstructTypeClause n3, OmpEol n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public OmpCancellationPointDirective(OmpPragma n0, OmpConstructTypeClause n1, OmpEol n2) {
      f0 = n0;
      f1 = new NodeToken("cancellation");
      f2 = new NodeToken("point");
      f3 = n1;
      f4 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

