//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <DECLARE>
 * f2 -> <TARGET>
 * f3 -> OmpEol()
 * f4 -> ( FunctionDefinitionOrDeclaration() )*
 * f5 -> OmpPragma()
 * f6 -> <END>
 * f7 -> <DECLARE>
 * f8 -> <TARGET>
 */
public class OmpDeclareTargetDirective implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeToken f2;
   public OmpEol f3;
   public NodeListOptional f4;
   public OmpPragma f5;
   public NodeToken f6;
   public NodeToken f7;
   public NodeToken f8;

   public OmpDeclareTargetDirective(OmpPragma n0, NodeToken n1, NodeToken n2, OmpEol n3, NodeListOptional n4, OmpPragma n5, NodeToken n6, NodeToken n7, NodeToken n8) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
   }

   public OmpDeclareTargetDirective(OmpPragma n0, OmpEol n1, NodeListOptional n2, OmpPragma n3) {
      f0 = n0;
      f1 = new NodeToken("declare");
      f2 = new NodeToken("target");
      f3 = n1;
      f4 = n2;
      f5 = n3;
      f6 = new NodeToken("end");
      f7 = new NodeToken("declare");
      f8 = new NodeToken("target");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

