//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <LINEAR>
 * f1 -> "("
 * f2 -> VariableList()
 * f3 -> ( <COLON> Expression() )?
 * f4 -> ")"
 */
public class OmpLinearClause implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public VariableList f2;
   public NodeOptional f3;
   public NodeToken f4;

   public OmpLinearClause(NodeToken n0, NodeToken n1, VariableList n2, NodeOptional n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public OmpLinearClause(VariableList n0, NodeOptional n1) {
      f0 = new NodeToken("linear");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = n1;
      f4 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

