//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <SIMD>
 * f2 -> ( OmpSimdClauseList() )?
 * f3 -> OmpEol()
 * f4 -> OmpForHeader()
 * f5 -> Statement()
 */
public class OmpSimdConstruct implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeOptional f2;
   public OmpEol f3;
   public OmpForHeader f4;
   public Statement f5;

   public OmpSimdConstruct(OmpPragma n0, NodeToken n1, NodeOptional n2, OmpEol n3, OmpForHeader n4, Statement n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public OmpSimdConstruct(OmpPragma n0, NodeOptional n1, OmpEol n2, OmpForHeader n3, Statement n4) {
      f0 = n0;
      f1 = new NodeToken("simd");
      f2 = n1;
      f3 = n2;
      f4 = n3;
      f5 = n4;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

