//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpIfTaskLoopClause()
 *       | OmpSharedClause()
 *       | OmpPrivateClause()
 *       | OmpFirstPrivateClause()
 *       | OmpLastPrivateClause()
 *       | OmpDfltSharedClause()
 *       | OmpDfltNoneClause()
 *       | OmpGrainSizeClause()
 *       | OmpNumTasksClause()
 *       | OmpCollapseClause()
 *       | OmpFinalClause()
 *       | OmpPriorityClause()
 *       | OmpUntiedClause()
 *       | OmpMergeableClause()
 *       | OmpNoGroupClause()
 */
public class OmpTaskLoopClause implements Node {
   public NodeChoice f0;

   public OmpTaskLoopClause(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

