//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <TARGET>
 * f2 -> <ENTER>
 * f3 -> <DATA>
 * f4 -> ( OmpTargetEnterDataClauseList() )?
 */
public class OmpTargetEnterDataConstruct implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeOptional f4;

   public OmpTargetEnterDataConstruct(OmpPragma n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeOptional n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public OmpTargetEnterDataConstruct(OmpPragma n0, NodeOptional n1) {
      f0 = n0;
      f1 = new NodeToken("target");
      f2 = new NodeToken("enter");
      f3 = new NodeToken("data");
      f4 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

