//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> OmpPragma()
 * f1 -> <TARGET>
 * f2 -> <TEAMS>
 * f3 -> <DISTRIBUTE>
 * f4 -> <PARALLEL>
 * f5 -> <FOR>
 * f6 -> ( OmpTargetTeamsDistributeParallelForClauseList() )?
 * f7 -> OmpEol()
 * f8 -> OmpForHeader()
 * f9 -> Statement()
 */
public class OmpTargetTeamsDistributeParallelForConstruct implements Node {
   public OmpPragma f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeToken f5;
   public NodeOptional f6;
   public OmpEol f7;
   public OmpForHeader f8;
   public Statement f9;

   public OmpTargetTeamsDistributeParallelForConstruct(OmpPragma n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeToken n4, NodeToken n5, NodeOptional n6, OmpEol n7, OmpForHeader n8, Statement n9) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
   }

   public OmpTargetTeamsDistributeParallelForConstruct(OmpPragma n0, NodeOptional n1, OmpEol n2, OmpForHeader n3, Statement n4) {
      f0 = n0;
      f1 = new NodeToken("target");
      f2 = new NodeToken("teams");
      f3 = new NodeToken("distribute");
      f4 = new NodeToken("parallel");
      f5 = new NodeToken("for");
      f6 = n1;
      f7 = n2;
      f8 = n3;
      f9 = n4;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

